package org.ohjic.mem.dao;

import java.util.List;

import org.ohjic.mem.model.Cgroup;

public interface CgroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    int deleteByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    int insert(Cgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    int insertSelective(Cgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    Cgroup selectByPrimaryKey(Integer no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    int updateByPrimaryKeySelective(Cgroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cGroup
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    int updateByPrimaryKey(Cgroup record);
    
    List<Cgroup> selectCgroupList(Cgroup record);
}