package org.ohjic.mem.dao;

import org.ohjic.mem.model.ChurchUseNumber;

public interface ChurchUseNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    int deleteByPrimaryKey(String churchCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    int insert(ChurchUseNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    int insertSelective(ChurchUseNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    ChurchUseNumber selectByPrimaryKey(String churchCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    int updateByPrimaryKeySelective(ChurchUseNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table church_use_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    int updateByPrimaryKey(ChurchUseNumber record);
}