package org.ohjic.mem.dao;

import org.ohjic.mem.model.Finmember;
import org.ohjic.mem.model.FinmemberKey;
import org.ohjic.mem.model.Kyo;

public interface FinmemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    int deleteByPrimaryKey(FinmemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    int insert(Finmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    int insertSelective(Finmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    Finmember selectByPrimaryKey(FinmemberKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    int updateByPrimaryKeySelective(Finmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finMember
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    int updateByPrimaryKey(Finmember record);
    
    
    int updatePartnerNameByDeath(Kyo kyo);
}