package org.ohjic.mem.dao;

import org.ohjic.mem.model.Manager;
import org.ohjic.mem.model.ManagerWithBLOBs;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int deleteByPrimaryKey(Integer managerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int insert(ManagerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int insertSelective(ManagerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    ManagerWithBLOBs selectByPrimaryKey(Integer managerNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int updateByPrimaryKeySelective(ManagerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ManagerWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    int updateByPrimaryKey(Manager record);
}