package org.ohjic.mem.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ohjic.mem.model.Kyo;
import org.ohjic.mem.model.Member;
import org.ohjic.mem.model.MemberWithBLOBs;
import org.ohjic.mem.vo.TidsVo;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int insert(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int insertSelective(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	MemberWithBLOBs selectByPrimaryKey(@Param("church") String church, @Param("tid") Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int updateByPrimaryKeySelective(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Aug 09 13:52:35 KST 2016
	 */
	int updateByPrimaryKey(Member record);

	Member selectMemberByMemberNameAndMemberNameDistinct(@Param("church") String church, @Param("memberName") String memberName, @Param("memberNameDistinct") String memberNameDistinct);
	
	Member selectLatestMemberByTids(TidsVo vo);

	List<Member> selectMemberList(Kyo kyo);

	/**
	 * 성도조회
	 * @param member
	 * @return
	 */
	List<Member>selectMember(Member member);
}