package org.ohjic.mem.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ohjic.mem.model.Kyo;
import org.ohjic.mem.model.Member;
import org.ohjic.mem.model.MemberWithBLOBs;
import org.ohjic.mem.vo.TidsVo;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int deleteByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int insert(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int insertSelective(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	MemberWithBLOBs selectByPrimaryKey(Integer tid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int updateByPrimaryKeySelective(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(MemberWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	int updateByPrimaryKey(Member record);

	Member selectMemberByMemberNameAndMemberNameDistinct(@Param("church") String church, @Param("memberName") String memberName, @Param("memberNameDistinct") String memberNameDistinct);
	
	Member selectLatestMemberByTids(TidsVo vo);

	List<Member> selectMemberList(Kyo kyo);

	/**
	 * ?��?��조회
	 * @param member
	 * @return
	 */
	List<Member>selectMember(Member member);

	MemberWithBLOBs selectByPrimaryKey(String church, Integer tid);
}