package org.ohjic.mem.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.ohjic.mem.model.Namecode;

public interface NamecodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	int deleteByPrimaryKey(Integer no);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	int insert(Namecode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	int insertSelective(Namecode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	Namecode selectByPrimaryKey(Integer no);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	int updateByPrimaryKeySelective(Namecode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nameCode
	 * @mbg.generated  Wed May 09 17:54:04 KST 2018
	 */
	int updateByPrimaryKey(Namecode record);

	/**
	 * 
	 * @param church("kyo"+churchCode)
	 * @param type
	 * @return
	 */
	List<Namecode> selectCodeList(@Param("church") String church, @Param("type") String type);

	Namecode selectCode(String church, String type, Integer no);
}