package org.ohjic.mem.dao;

import org.ohjic.mem.model.Worshipgroup;
import org.ohjic.mem.vo.YearVo;

public interface WorshipgroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worshipGroup
	 * @mbg.generated  Wed Dec 21 21:38:10 KST 2016
	 */
	int insert(Worshipgroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table worshipGroup
	 * @mbg.generated  Wed Dec 21 21:38:10 KST 2016
	 */
	int insertSelective(Worshipgroup record);
	
	int insertWorshipGroupForNextYear(YearVo yearVo);
}