package org.ohjic.mem.model;

import java.util.Date;

public class AuthInCharge extends Kyo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_in_charge.auth_in_charge_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	private Integer authInChargeIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_in_charge.auth_set_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	private Integer authSetIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_in_charge.manager_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	private Integer managerIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_in_charge.group_no
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	private Integer groupNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_in_charge.reg_date
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	private Date regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_in_charge.auth_in_charge_idx
	 * @return  the value of auth_in_charge.auth_in_charge_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public Integer getAuthInChargeIdx() {
		return authInChargeIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_in_charge.auth_in_charge_idx
	 * @param authInChargeIdx  the value for auth_in_charge.auth_in_charge_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public void setAuthInChargeIdx(Integer authInChargeIdx) {
		this.authInChargeIdx = authInChargeIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_in_charge.auth_set_idx
	 * @return  the value of auth_in_charge.auth_set_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public Integer getAuthSetIdx() {
		return authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_in_charge.auth_set_idx
	 * @param authSetIdx  the value for auth_in_charge.auth_set_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public void setAuthSetIdx(Integer authSetIdx) {
		this.authSetIdx = authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_in_charge.manager_idx
	 * @return  the value of auth_in_charge.manager_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public Integer getManagerIdx() {
		return managerIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_in_charge.manager_idx
	 * @param managerIdx  the value for auth_in_charge.manager_idx
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public void setManagerIdx(Integer managerIdx) {
		this.managerIdx = managerIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_in_charge.group_no
	 * @return  the value of auth_in_charge.group_no
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public Integer getGroupNo() {
		return groupNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_in_charge.group_no
	 * @param groupNo  the value for auth_in_charge.group_no
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public void setGroupNo(Integer groupNo) {
		this.groupNo = groupNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_in_charge.reg_date
	 * @return  the value of auth_in_charge.reg_date
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_in_charge.reg_date
	 * @param regDate  the value for auth_in_charge.reg_date
	 * @mbg.generated  Thu Nov 02 16:17:48 KST 2017
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
}