package org.ohjic.mem.model;

public class AuthGroupKey extends Kyo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer authSetIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer sort_no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer auth_type_idx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.auth_set_idx
	 * @return  the value of auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getAuthSetIdx() {
		return authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.auth_set_idx
	 * @param authSetIdx  the value for auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setAuthSetIdx(Integer authSetIdx) {
		this.authSetIdx = authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.sort_no
	 * @return  the value of auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getSort_no() {
		return sort_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.sort_no
	 * @param sort_no  the value for auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setSort_no(Integer sort_no) {
		this.sort_no = sort_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.auth_type_idx
	 * @return  the value of auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getAuth_type_idx() {
		return auth_type_idx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.auth_type_idx
	 * @param auth_type_idx  the value for auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setAuth_type_idx(Integer auth_type_idx) {
		this.auth_type_idx = auth_type_idx;
	}
}