package org.ohjic.mem.model;

import java.util.Date;

public class AuthGroup extends AuthGroupKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.value
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.reg_date
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Date regDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.value
	 * @return  the value of auth_group.value
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.value
	 * @param value  the value for auth_group.value
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setValue(Integer value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.reg_date
	 * @return  the value of auth_group.reg_date
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.reg_date
	 * @param regDate  the value for auth_group.reg_date
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}
}