package org.ohjic.mem.model;

public class AuthGroupKey extends Kyo{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer authSetIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer sortNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	private Integer authTypeIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.auth_set_idx
	 * @return  the value of auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getAuthSetIdx() {
		return authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.auth_set_idx
	 * @param authSetIdx  the value for auth_group.auth_set_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setAuthSetIdx(Integer authSetIdx) {
		this.authSetIdx = authSetIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.sort_no
	 * @return  the value of auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getSortNo() {
		return sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.sort_no
	 * @param sort_no  the value for auth_group.sort_no
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column auth_group.auth_type_idx
	 * @return  the value of auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public Integer getAuthTypeIdx() {
		return authTypeIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column auth_group.auth_type_idx
	 * @param auth_type_idx  the value for auth_group.auth_type_idx
	 * @mbg.generated  Wed Dec 21 18:33:33 KST 2016
	 */
	public void setAuthTypeIdx(Integer authTypeIdx) {
		this.authTypeIdx = authTypeIdx;
	}
}