package org.ohjic.mem.model;

public class Cgroup extends Kyo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.no
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.ord
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private Integer ord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.depth1
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private Integer depth1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.depth2
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private Integer depth2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.depth1Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private String depth1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.depth2Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private String depth2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.depth
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private byte[] groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.groupName
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private String groupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cGroup.display_status
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    private Integer displayStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.no
     *
     * @return the value of cGroup.no
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.no
     *
     * @param no the value for cGroup.no
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.ord
     *
     * @return the value of cGroup.ord
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.ord
     *
     * @param ord the value for cGroup.ord
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.depth1
     *
     * @return the value of cGroup.depth1
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public Integer getDepth1() {
        return depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.depth1
     *
     * @param depth1 the value for cGroup.depth1
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setDepth1(Integer depth1) {
        this.depth1 = depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.depth2
     *
     * @return the value of cGroup.depth2
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public Integer getDepth2() {
        return depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.depth2
     *
     * @param depth2 the value for cGroup.depth2
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setDepth2(Integer depth2) {
        this.depth2 = depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.depth1Name
     *
     * @return the value of cGroup.depth1Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public String getDepth1Name() {
        return depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.depth1Name
     *
     * @param depth1Name the value for cGroup.depth1Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setDepth1Name(String depth1Name) {
        this.depth1Name = depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.depth2Name
     *
     * @return the value of cGroup.depth2Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public String getDepth2Name() {
        return depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.depth2Name
     *
     * @param depth2Name the value for cGroup.depth2Name
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setDepth2Name(String depth2Name) {
        this.depth2Name = depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.depth
     *
     * @return the value of cGroup.depth
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public byte[] getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.depth
     *
     * @param groupName the value for cGroup.depth
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setGroupName(byte[] groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.groupName
     *
     * @return the value of cGroup.groupName
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.groupName
     *
     * @param groupname the value for cGroup.groupName
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cGroup.display_status
     *
     * @return the value of cGroup.display_status
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public Integer getDisplayStatus() {
        return displayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cGroup.display_status
     *
     * @param displayStatus the value for cGroup.display_status
     *
     * @mbg.generated Wed Jan 04 10:14:28 KST 2017
     */
    public void setDisplayStatus(Integer displayStatus) {
        this.displayStatus = displayStatus;
    }
}