package org.ohjic.mem.model;

import java.util.Date;

public class ChurchUseNumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column church_use_number.church_code
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    private String churchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column church_use_number.church_name
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    private String churchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column church_use_number.limit
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    private Integer limit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column church_use_number.kyo_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    private Integer kyoNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column church_use_number.regi_date
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    private Date regiDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column church_use_number.church_code
     *
     * @return the value of church_use_number.church_code
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public String getChurchCode() {
        return churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column church_use_number.church_code
     *
     * @param churchCode the value for church_use_number.church_code
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public void setChurchCode(String churchCode) {
        this.churchCode = churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column church_use_number.church_name
     *
     * @return the value of church_use_number.church_name
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public String getChurchName() {
        return churchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column church_use_number.church_name
     *
     * @param churchName the value for church_use_number.church_name
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public void setChurchName(String churchName) {
        this.churchName = churchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column church_use_number.limit
     *
     * @return the value of church_use_number.limit
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column church_use_number.limit
     *
     * @param limit the value for church_use_number.limit
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column church_use_number.kyo_number
     *
     * @return the value of church_use_number.kyo_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public Integer getKyoNumber() {
        return kyoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column church_use_number.kyo_number
     *
     * @param kyoNumber the value for church_use_number.kyo_number
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public void setKyoNumber(Integer kyoNumber) {
        this.kyoNumber = kyoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column church_use_number.regi_date
     *
     * @return the value of church_use_number.regi_date
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public Date getRegiDate() {
        return regiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column church_use_number.regi_date
     *
     * @param regiDate the value for church_use_number.regi_date
     *
     * @mbg.generated Tue Oct 18 12:48:26 KST 2016
     */
    public void setRegiDate(Date regiDate) {
        this.regiDate = regiDate;
    }
}