package org.ohjic.mem.model;

public class Churchinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchCode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private Integer churchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String churchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.religiousBody
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String religiousBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchSize
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private Integer churchSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.ministerName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String ministerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchAddress1
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String churchAddress1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchAddress2
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String churchAddress2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchZipcode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String churchZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.churchPhone
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String churchPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.adminId
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.homepage
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String homepage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.regiDate
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private Integer regiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.deleteFlag
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private byte[] deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.point
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private Integer point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.version
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column churchInfo.oldProgram
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    private String oldProgram;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchCode
     *
     * @return the value of churchInfo.churchCode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public Integer getChurchCode() {
        return churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchCode
     *
     * @param churchCode the value for churchInfo.churchCode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchCode(Integer churchCode) {
        this.churchCode = churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchName
     *
     * @return the value of churchInfo.churchName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getChurchName() {
        return churchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchName
     *
     * @param churchName the value for churchInfo.churchName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchName(String churchName) {
        this.churchName = churchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.religiousBody
     *
     * @return the value of churchInfo.religiousBody
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getReligiousBody() {
        return religiousBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.religiousBody
     *
     * @param religiousBody the value for churchInfo.religiousBody
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setReligiousBody(String religiousBody) {
        this.religiousBody = religiousBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchSize
     *
     * @return the value of churchInfo.churchSize
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public Integer getChurchSize() {
        return churchSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchSize
     *
     * @param churchSize the value for churchInfo.churchSize
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchSize(Integer churchSize) {
        this.churchSize = churchSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.ministerName
     *
     * @return the value of churchInfo.ministerName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getMinisterName() {
        return ministerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.ministerName
     *
     * @param ministerName the value for churchInfo.ministerName
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setMinisterName(String ministerName) {
        this.ministerName = ministerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchAddress1
     *
     * @return the value of churchInfo.churchAddress1
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getChurchAddress1() {
        return churchAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchAddress1
     *
     * @param churchAddress1 the value for churchInfo.churchAddress1
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchAddress1(String churchAddress1) {
        this.churchAddress1 = churchAddress1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchAddress2
     *
     * @return the value of churchInfo.churchAddress2
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getChurchAddress2() {
        return churchAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchAddress2
     *
     * @param churchAddress2 the value for churchInfo.churchAddress2
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchAddress2(String churchAddress2) {
        this.churchAddress2 = churchAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchZipcode
     *
     * @return the value of churchInfo.churchZipcode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getChurchZipcode() {
        return churchZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchZipcode
     *
     * @param churchZipcode the value for churchInfo.churchZipcode
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchZipcode(String churchZipcode) {
        this.churchZipcode = churchZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.churchPhone
     *
     * @return the value of churchInfo.churchPhone
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getChurchPhone() {
        return churchPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.churchPhone
     *
     * @param churchPhone the value for churchInfo.churchPhone
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setChurchPhone(String churchPhone) {
        this.churchPhone = churchPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.adminId
     *
     * @return the value of churchInfo.adminId
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.adminId
     *
     * @param adminId the value for churchInfo.adminId
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.homepage
     *
     * @return the value of churchInfo.homepage
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.homepage
     *
     * @param homepage the value for churchInfo.homepage
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.regiDate
     *
     * @return the value of churchInfo.regiDate
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public Integer getRegiDate() {
        return regiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.regiDate
     *
     * @param regiDate the value for churchInfo.regiDate
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setRegiDate(Integer regiDate) {
        this.regiDate = regiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.deleteFlag
     *
     * @return the value of churchInfo.deleteFlag
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public byte[] getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.deleteFlag
     *
     * @param deleteFlag the value for churchInfo.deleteFlag
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setDeleteFlag(byte[] deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.point
     *
     * @return the value of churchInfo.point
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.point
     *
     * @param point the value for churchInfo.point
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.version
     *
     * @return the value of churchInfo.version
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.version
     *
     * @param version the value for churchInfo.version
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column churchInfo.oldProgram
     *
     * @return the value of churchInfo.oldProgram
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public String getOldProgram() {
        return oldProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column churchInfo.oldProgram
     *
     * @param oldProgram the value for churchInfo.oldProgram
     *
     * @mbggenerated Thu Aug 25 16:45:12 KST 2016
     */
    public void setOldProgram(String oldProgram) {
        this.oldProgram = oldProgram;
    }
}