package org.ohjic.mem.model;

public class FinmemberKey extends Kyo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.mem_type
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer memType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.pid
     *
     * @return the value of finMember.pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.pid
     *
     * @param pid the value for finMember.pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.mem_type
     *
     * @return the value of finMember.mem_type
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getMemType() {
        return memType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.mem_type
     *
     * @param memType the value for finMember.mem_type
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setMemType(Integer memType) {
        this.memType = memType;
    }
}