package org.ohjic.mem.model;

public class Finmember extends FinmemberKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.envNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String envNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.partner_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String partnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.group_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.addr
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.phone
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.birth_year
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Short birthYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.birth_date
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Short birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.permitNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String permitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.leaderName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.bankName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.standardCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer standardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.accountNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.accountHolder
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String accountHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.prevCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String prevCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.etc
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String etc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.merged_pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer mergedPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.merged_tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private Integer mergedTid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.vpa_account
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String vpaAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column finMember.vpa_trnx_id
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    private String vpaTrnxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.envNo
     *
     * @return the value of finMember.envNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getEnvNo() {
        return envNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.envNo
     *
     * @param envNo the value for finMember.envNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setEnvNo(String envNo) {
        this.envNo = envNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.tid
     *
     * @return the value of finMember.tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.tid
     *
     * @param tid the value for finMember.tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.name
     *
     * @return the value of finMember.name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.name
     *
     * @param name the value for finMember.name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.partner_name
     *
     * @return the value of finMember.partner_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.partner_name
     *
     * @param partnerName the value for finMember.partner_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.group_name
     *
     * @return the value of finMember.group_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.group_name
     *
     * @param groupName the value for finMember.group_name
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.addr
     *
     * @return the value of finMember.addr
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.addr
     *
     * @param addr the value for finMember.addr
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.phone
     *
     * @return the value of finMember.phone
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.phone
     *
     * @param phone the value for finMember.phone
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.birth_year
     *
     * @return the value of finMember.birth_year
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Short getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.birth_year
     *
     * @param birthYear the value for finMember.birth_year
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setBirthYear(Short birthYear) {
        this.birthYear = birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.birth_date
     *
     * @return the value of finMember.birth_date
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Short getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.birth_date
     *
     * @param birthDate the value for finMember.birth_date
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setBirthDate(Short birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.permitNo
     *
     * @return the value of finMember.permitNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getPermitNo() {
        return permitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.permitNo
     *
     * @param permitNo the value for finMember.permitNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setPermitNo(String permitNo) {
        this.permitNo = permitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.leaderName
     *
     * @return the value of finMember.leaderName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.leaderName
     *
     * @param leaderName the value for finMember.leaderName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.bankName
     *
     * @return the value of finMember.bankName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.bankName
     *
     * @param bankName the value for finMember.bankName
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.standardCode
     *
     * @return the value of finMember.standardCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getStandardCode() {
        return standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.standardCode
     *
     * @param standardCode the value for finMember.standardCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setStandardCode(Integer standardCode) {
        this.standardCode = standardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.accountNo
     *
     * @return the value of finMember.accountNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.accountNo
     *
     * @param accountNo the value for finMember.accountNo
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.accountHolder
     *
     * @return the value of finMember.accountHolder
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getAccountHolder() {
        return accountHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.accountHolder
     *
     * @param accountHolder the value for finMember.accountHolder
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setAccountHolder(String accountHolder) {
        this.accountHolder = accountHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.prevCode
     *
     * @return the value of finMember.prevCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getPrevCode() {
        return prevCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.prevCode
     *
     * @param prevCode the value for finMember.prevCode
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setPrevCode(String prevCode) {
        this.prevCode = prevCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.etc
     *
     * @return the value of finMember.etc
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getEtc() {
        return etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.etc
     *
     * @param etc the value for finMember.etc
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setEtc(String etc) {
        this.etc = etc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.merged_pid
     *
     * @return the value of finMember.merged_pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getMergedPid() {
        return mergedPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.merged_pid
     *
     * @param mergedPid the value for finMember.merged_pid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setMergedPid(Integer mergedPid) {
        this.mergedPid = mergedPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.merged_tid
     *
     * @return the value of finMember.merged_tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public Integer getMergedTid() {
        return mergedTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.merged_tid
     *
     * @param mergedTid the value for finMember.merged_tid
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setMergedTid(Integer mergedTid) {
        this.mergedTid = mergedTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.vpa_account
     *
     * @return the value of finMember.vpa_account
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getVpaAccount() {
        return vpaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.vpa_account
     *
     * @param vpaAccount the value for finMember.vpa_account
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setVpaAccount(String vpaAccount) {
        this.vpaAccount = vpaAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column finMember.vpa_trnx_id
     *
     * @return the value of finMember.vpa_trnx_id
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public String getVpaTrnxId() {
        return vpaTrnxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column finMember.vpa_trnx_id
     *
     * @param vpaTrnxId the value for finMember.vpa_trnx_id
     *
     * @mbg.generated Wed Jan 04 14:28:19 KST 2017
     */
    public void setVpaTrnxId(String vpaTrnxId) {
        this.vpaTrnxId = vpaTrnxId;
    }
}