package org.ohjic.mem.model;

public class GroupInfo extends Kyo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.info_idx
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private Integer info_idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.year
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_no
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private Integer group_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.group_type
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String group_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.age_band
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String age_band;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_day
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_day;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_time
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_time_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_time_text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_place
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_place_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_place_text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.meeting_area
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String meeting_area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item1
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item2
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item3
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item4
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item5
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item6
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item7
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item8
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_info.free_item9
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    private String free_item9;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.info_idx
     *
     * @return the value of group_info.info_idx
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public Integer getInfo_idx() {
        return info_idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.info_idx
     *
     * @param info_idx the value for group_info.info_idx
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setInfo_idx(Integer info_idx) {
        this.info_idx = info_idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.year
     *
     * @return the value of group_info.year
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.year
     *
     * @param year the value for group_info.year
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_no
     *
     * @return the value of group_info.group_no
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public Integer getGroup_no() {
        return group_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_no
     *
     * @param group_no the value for group_info.group_no
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setGroup_no(Integer group_no) {
        this.group_no = group_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.group_type
     *
     * @return the value of group_info.group_type
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getGroup_type() {
        return group_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.group_type
     *
     * @param group_type the value for group_info.group_type
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setGroup_type(String group_type) {
        this.group_type = group_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.age_band
     *
     * @return the value of group_info.age_band
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getAge_band() {
        return age_band;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.age_band
     *
     * @param age_band the value for group_info.age_band
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setAge_band(String age_band) {
        this.age_band = age_band;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_day
     *
     * @return the value of group_info.meeting_day
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_day() {
        return meeting_day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_day
     *
     * @param meeting_day the value for group_info.meeting_day
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_day(String meeting_day) {
        this.meeting_day = meeting_day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_time
     *
     * @return the value of group_info.meeting_time
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_time() {
        return meeting_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_time
     *
     * @param meeting_time the value for group_info.meeting_time
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_time(String meeting_time) {
        this.meeting_time = meeting_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_time_text
     *
     * @return the value of group_info.meeting_time_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_time_text() {
        return meeting_time_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_time_text
     *
     * @param meeting_time_text the value for group_info.meeting_time_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_time_text(String meeting_time_text) {
        this.meeting_time_text = meeting_time_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_place
     *
     * @return the value of group_info.meeting_place
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_place() {
        return meeting_place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_place
     *
     * @param meeting_place the value for group_info.meeting_place
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_place(String meeting_place) {
        this.meeting_place = meeting_place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_place_text
     *
     * @return the value of group_info.meeting_place_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_place_text() {
        return meeting_place_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_place_text
     *
     * @param meeting_place_text the value for group_info.meeting_place_text
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_place_text(String meeting_place_text) {
        this.meeting_place_text = meeting_place_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.meeting_area
     *
     * @return the value of group_info.meeting_area
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getMeeting_area() {
        return meeting_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.meeting_area
     *
     * @param meeting_area the value for group_info.meeting_area
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setMeeting_area(String meeting_area) {
        this.meeting_area = meeting_area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item1
     *
     * @return the value of group_info.free_item1
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item1() {
        return free_item1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item1
     *
     * @param free_item1 the value for group_info.free_item1
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item1(String free_item1) {
        this.free_item1 = free_item1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item2
     *
     * @return the value of group_info.free_item2
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item2() {
        return free_item2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item2
     *
     * @param free_item2 the value for group_info.free_item2
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item2(String free_item2) {
        this.free_item2 = free_item2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item3
     *
     * @return the value of group_info.free_item3
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item3() {
        return free_item3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item3
     *
     * @param free_item3 the value for group_info.free_item3
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item3(String free_item3) {
        this.free_item3 = free_item3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item4
     *
     * @return the value of group_info.free_item4
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item4() {
        return free_item4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item4
     *
     * @param free_item4 the value for group_info.free_item4
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item4(String free_item4) {
        this.free_item4 = free_item4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item5
     *
     * @return the value of group_info.free_item5
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item5() {
        return free_item5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item5
     *
     * @param free_item5 the value for group_info.free_item5
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item5(String free_item5) {
        this.free_item5 = free_item5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item6
     *
     * @return the value of group_info.free_item6
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item6() {
        return free_item6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item6
     *
     * @param free_item6 the value for group_info.free_item6
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item6(String free_item6) {
        this.free_item6 = free_item6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item7
     *
     * @return the value of group_info.free_item7
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item7() {
        return free_item7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item7
     *
     * @param free_item7 the value for group_info.free_item7
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item7(String free_item7) {
        this.free_item7 = free_item7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item8
     *
     * @return the value of group_info.free_item8
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item8() {
        return free_item8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item8
     *
     * @param free_item8 the value for group_info.free_item8
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item8(String free_item8) {
        this.free_item8 = free_item8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_info.free_item9
     *
     * @return the value of group_info.free_item9
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public String getFree_item9() {
        return free_item9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_info.free_item9
     *
     * @param free_item9 the value for group_info.free_item9
     *
     * @mbg.generated Tue Dec 27 08:52:14 KST 2016
     */
    public void setFree_item9(String free_item9) {
        this.free_item9 = free_item9;
    }
}