package org.ohjic.mem.model;

import java.util.Date;

public class Historypgrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.history_idx
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Integer historyIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.p_grade_name
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private String pGradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.p_grade
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Integer pGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.p_grade_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Date pGradeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.p_grade_minister
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private String pGradeMinister;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.p_grade_church
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private String pGradeChurch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.regi_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Date regiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.managerNo
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Integer managerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyPgrade.tid
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.history_idx
     *
     * @return the value of historyPgrade.history_idx
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Integer getHistoryIdx() {
        return historyIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.history_idx
     *
     * @param historyIdx the value for historyPgrade.history_idx
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setHistoryIdx(Integer historyIdx) {
        this.historyIdx = historyIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.p_grade_name
     *
     * @return the value of historyPgrade.p_grade_name
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public String getpGradeName() {
        return pGradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.p_grade_name
     *
     * @param pGradeName the value for historyPgrade.p_grade_name
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setpGradeName(String pGradeName) {
        this.pGradeName = pGradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.p_grade
     *
     * @return the value of historyPgrade.p_grade
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Integer getpGrade() {
        return pGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.p_grade
     *
     * @param pGrade the value for historyPgrade.p_grade
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setpGrade(Integer pGrade) {
        this.pGrade = pGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.p_grade_date
     *
     * @return the value of historyPgrade.p_grade_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Date getpGradeDate() {
        return pGradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.p_grade_date
     *
     * @param pGradeDate the value for historyPgrade.p_grade_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setpGradeDate(Date pGradeDate) {
        this.pGradeDate = pGradeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.p_grade_minister
     *
     * @return the value of historyPgrade.p_grade_minister
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public String getpGradeMinister() {
        return pGradeMinister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.p_grade_minister
     *
     * @param pGradeMinister the value for historyPgrade.p_grade_minister
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setpGradeMinister(String pGradeMinister) {
        this.pGradeMinister = pGradeMinister;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.p_grade_church
     *
     * @return the value of historyPgrade.p_grade_church
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public String getpGradeChurch() {
        return pGradeChurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.p_grade_church
     *
     * @param pGradeChurch the value for historyPgrade.p_grade_church
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setpGradeChurch(String pGradeChurch) {
        this.pGradeChurch = pGradeChurch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.regi_date
     *
     * @return the value of historyPgrade.regi_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Date getRegiDate() {
        return regiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.regi_date
     *
     * @param regiDate the value for historyPgrade.regi_date
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setRegiDate(Date regiDate) {
        this.regiDate = regiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.managerNo
     *
     * @return the value of historyPgrade.managerNo
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Integer getManagerNo() {
        return managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.managerNo
     *
     * @param managerNo the value for historyPgrade.managerNo
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setManagerNo(Integer managerNo) {
        this.managerNo = managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyPgrade.tid
     *
     * @return the value of historyPgrade.tid
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyPgrade.tid
     *
     * @param tid the value for historyPgrade.tid
     *
     * @mbg.generated Fri Dec 15 15:31:43 KST 2017
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}