package org.ohjic.mem.model;

import java.util.Date;

public class Historychristening {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.history_idx
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Integer historyIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.christening_name
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private String christeningName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.christening
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Integer christening;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.christening_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Date christeningDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.christening_church
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private String christeningChurch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.christening_minister
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private String christeningMinister;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.regi_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Date regiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.managerNo
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Integer managerNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column historyChristening.tid
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	private Integer tid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.history_idx
	 * @return  the value of historyChristening.history_idx
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Integer getHistoryIdx() {
		return historyIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.history_idx
	 * @param historyIdx  the value for historyChristening.history_idx
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setHistoryIdx(Integer historyIdx) {
		this.historyIdx = historyIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.christening_name
	 * @return  the value of historyChristening.christening_name
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public String getChristeningName() {
		return christeningName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.christening_name
	 * @param pGradeName  the value for historyChristening.christening_name
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setChristeningName(String christeningName) {
		this.christeningName = christeningName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.christening
	 * @return  the value of historyChristening.christening
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Integer getChristening() {
		return christening;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.christening
	 * @param christening  the value for historyChristening.christening
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setChristening(Integer christening) {
		this.christening = christening;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.christening_date
	 * @return  the value of historyChristening.christening_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Date getChristeningDate() {
		return christeningDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.christening_date
	 * @param christeningDate  the value for historyChristening.christening_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setChristeningDate(Date christeningDate) {
		this.christeningDate = christeningDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.christening_church
	 * @return  the value of historyChristening.christening_church
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public String getChristeningChurch() {
		return christeningChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.christening_church
	 * @param christeningChurch  the value for historyChristening.christening_church
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setChristeningChurch(String christeningChurch) {
		this.christeningChurch = christeningChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.christening_minister
	 * @return  the value of historyChristening.christening_minister
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public String getChristeningMinister() {
		return christeningMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.christening_minister
	 * @param christeningMinister  the value for historyChristening.christening_minister
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setChristeningMinister(String christeningMinister) {
		this.christeningMinister = christeningMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.regi_date
	 * @return  the value of historyChristening.regi_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Date getRegiDate() {
		return regiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.regi_date
	 * @param regiDate  the value for historyChristening.regi_date
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setRegiDate(Date regiDate) {
		this.regiDate = regiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.managerNo
	 * @return  the value of historyChristening.managerNo
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Integer getManagerNo() {
		return managerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.managerNo
	 * @param managerNo  the value for historyChristening.managerNo
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setManagerNo(Integer managerNo) {
		this.managerNo = managerNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column historyChristening.tid
	 * @return  the value of historyChristening.tid
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column historyChristening.tid
	 * @param tid  the value for historyChristening.tid
	 * @mbg.generated  Fri Dec 15 15:31:43 KST 2017
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}
}