package org.ohjic.mem.model;

public class Kgrouplog extends Kyo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.start_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.end_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.sortNo
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer sortNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.attend_type
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String attendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.year
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.k_part_idx
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer kPartIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.group_no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer groupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.group_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth1_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String depth1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth2_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String depth2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth3_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String depth3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth4_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String depth4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth5_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String depth5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth1
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer depth1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth2
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer depth2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth3
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer depth3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth4
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer depth4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.depth5
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer depth5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.tid
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.position
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.position_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.position_ord
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer positionOrd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroupLog.chief
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    private Integer chief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.no
     *
     * @return the value of kGroupLog.no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.no
     *
     * @param no the value for kGroupLog.no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.start_date
     *
     * @return the value of kGroupLog.start_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.start_date
     *
     * @param startDate the value for kGroupLog.start_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setStartDate(Integer startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.end_date
     *
     * @return the value of kGroupLog.end_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.end_date
     *
     * @param endDate the value for kGroupLog.end_date
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setEndDate(Integer endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.sortNo
     *
     * @return the value of kGroupLog.sortNo
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getSortNo() {
        return sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.sortNo
     *
     * @param sortNo the value for kGroupLog.sortNo
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setSortNo(Integer sortNo) {
        this.sortNo = sortNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.attend_type
     *
     * @return the value of kGroupLog.attend_type
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getAttendType() {
        return attendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.attend_type
     *
     * @param attendType the value for kGroupLog.attend_type
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setAttendType(String attendType) {
        this.attendType = attendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.year
     *
     * @return the value of kGroupLog.year
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.year
     *
     * @param year the value for kGroupLog.year
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.k_part_idx
     *
     * @return the value of kGroupLog.k_part_idx
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getkPartIdx() {
        return kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.k_part_idx
     *
     * @param kPartIdx the value for kGroupLog.k_part_idx
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setkPartIdx(Integer kPartIdx) {
        this.kPartIdx = kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.group_no
     *
     * @return the value of kGroupLog.group_no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getGroupNo() {
        return groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.group_no
     *
     * @param groupNo the value for kGroupLog.group_no
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setGroupNo(Integer groupNo) {
        this.groupNo = groupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.group_name
     *
     * @return the value of kGroupLog.group_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.group_name
     *
     * @param groupName the value for kGroupLog.group_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth1_name
     *
     * @return the value of kGroupLog.depth1_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getDepth1Name() {
        return depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth1_name
     *
     * @param depth1Name the value for kGroupLog.depth1_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth1Name(String depth1Name) {
        this.depth1Name = depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth2_name
     *
     * @return the value of kGroupLog.depth2_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getDepth2Name() {
        return depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth2_name
     *
     * @param depth2Name the value for kGroupLog.depth2_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth2Name(String depth2Name) {
        this.depth2Name = depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth3_name
     *
     * @return the value of kGroupLog.depth3_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getDepth3Name() {
        return depth3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth3_name
     *
     * @param depth3Name the value for kGroupLog.depth3_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth3Name(String depth3Name) {
        this.depth3Name = depth3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth4_name
     *
     * @return the value of kGroupLog.depth4_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getDepth4Name() {
        return depth4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth4_name
     *
     * @param depth4Name the value for kGroupLog.depth4_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth4Name(String depth4Name) {
        this.depth4Name = depth4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth5_name
     *
     * @return the value of kGroupLog.depth5_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getDepth5Name() {
        return depth5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth5_name
     *
     * @param depth5Name the value for kGroupLog.depth5_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth5Name(String depth5Name) {
        this.depth5Name = depth5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth1
     *
     * @return the value of kGroupLog.depth1
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getDepth1() {
        return depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth1
     *
     * @param depth1 the value for kGroupLog.depth1
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth1(Integer depth1) {
        this.depth1 = depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth2
     *
     * @return the value of kGroupLog.depth2
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getDepth2() {
        return depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth2
     *
     * @param depth2 the value for kGroupLog.depth2
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth2(Integer depth2) {
        this.depth2 = depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth3
     *
     * @return the value of kGroupLog.depth3
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getDepth3() {
        return depth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth3
     *
     * @param depth3 the value for kGroupLog.depth3
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth3(Integer depth3) {
        this.depth3 = depth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth4
     *
     * @return the value of kGroupLog.depth4
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getDepth4() {
        return depth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth4
     *
     * @param depth4 the value for kGroupLog.depth4
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth4(Integer depth4) {
        this.depth4 = depth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.depth5
     *
     * @return the value of kGroupLog.depth5
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getDepth5() {
        return depth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.depth5
     *
     * @param depth5 the value for kGroupLog.depth5
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setDepth5(Integer depth5) {
        this.depth5 = depth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.tid
     *
     * @return the value of kGroupLog.tid
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.tid
     *
     * @param tid the value for kGroupLog.tid
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.position
     *
     * @return the value of kGroupLog.position
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.position
     *
     * @param position the value for kGroupLog.position
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.position_name
     *
     * @return the value of kGroupLog.position_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.position_name
     *
     * @param positionName the value for kGroupLog.position_name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.position_ord
     *
     * @return the value of kGroupLog.position_ord
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getPositionOrd() {
        return positionOrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.position_ord
     *
     * @param positionOrd the value for kGroupLog.position_ord
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setPositionOrd(Integer positionOrd) {
        this.positionOrd = positionOrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.name
     *
     * @return the value of kGroupLog.name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.name
     *
     * @param name the value for kGroupLog.name
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroupLog.chief
     *
     * @return the value of kGroupLog.chief
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public Integer getChief() {
        return chief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroupLog.chief
     *
     * @param chief the value for kGroupLog.chief
     *
     * @mbggenerated Wed Aug 31 22:00:43 KST 2016
     */
    public void setChief(Integer chief) {
        this.chief = chief;
    }
    
}