package org.ohjic.mem.model;

import java.util.Date;

public class Kgroup extends KgroupKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.k_part_idx
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer kPartIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth1
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer depth1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth2
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer depth2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth3
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer depth3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth4
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer depth4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth5
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer depth5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.ord
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer ord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth1_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String depth1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth2_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String depth2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth3_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String depth3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth4_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String depth4Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth5_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String depth5Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.depth
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private byte[] depth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.group_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.start_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.end_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Integer endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.reportType
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String reportType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.reg_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private Date regDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kGroup.reportItem
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    private String reportItem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.k_part_idx
     *
     * @return the value of kGroup.k_part_idx
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getkPartIdx() {
        return kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.k_part_idx
     *
     * @param kPartIdx the value for kGroup.k_part_idx
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setkPartIdx(Integer kPartIdx) {
        this.kPartIdx = kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth1
     *
     * @return the value of kGroup.depth1
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getDepth1() {
        return depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth1
     *
     * @param depth1 the value for kGroup.depth1
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth1(Integer depth1) {
        this.depth1 = depth1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth2
     *
     * @return the value of kGroup.depth2
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getDepth2() {
        return depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth2
     *
     * @param depth2 the value for kGroup.depth2
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth2(Integer depth2) {
        this.depth2 = depth2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth3
     *
     * @return the value of kGroup.depth3
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getDepth3() {
        return depth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth3
     *
     * @param depth3 the value for kGroup.depth3
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth3(Integer depth3) {
        this.depth3 = depth3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth4
     *
     * @return the value of kGroup.depth4
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getDepth4() {
        return depth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth4
     *
     * @param depth4 the value for kGroup.depth4
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth4(Integer depth4) {
        this.depth4 = depth4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth5
     *
     * @return the value of kGroup.depth5
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getDepth5() {
        return depth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth5
     *
     * @param depth5 the value for kGroup.depth5
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth5(Integer depth5) {
        this.depth5 = depth5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.ord
     *
     * @return the value of kGroup.ord
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.ord
     *
     * @param ord the value for kGroup.ord
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth1_name
     *
     * @return the value of kGroup.depth1_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getDepth1Name() {
        return depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth1_name
     *
     * @param depth1Name the value for kGroup.depth1_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth1Name(String depth1Name) {
        this.depth1Name = depth1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth2_name
     *
     * @return the value of kGroup.depth2_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getDepth2Name() {
        return depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth2_name
     *
     * @param depth2Name the value for kGroup.depth2_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth2Name(String depth2Name) {
        this.depth2Name = depth2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth3_name
     *
     * @return the value of kGroup.depth3_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getDepth3Name() {
        return depth3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth3_name
     *
     * @param depth3Name the value for kGroup.depth3_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth3Name(String depth3Name) {
        this.depth3Name = depth3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth4_name
     *
     * @return the value of kGroup.depth4_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getDepth4Name() {
        return depth4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth4_name
     *
     * @param depth4Name the value for kGroup.depth4_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth4Name(String depth4Name) {
        this.depth4Name = depth4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth5_name
     *
     * @return the value of kGroup.depth5_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getDepth5Name() {
        return depth5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth5_name
     *
     * @param depth5Name the value for kGroup.depth5_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth5Name(String depth5Name) {
        this.depth5Name = depth5Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.depth
     *
     * @return the value of kGroup.depth
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public byte[] getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.depth
     *
     * @param depth the value for kGroup.depth
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setDepth(byte[] depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.group_name
     *
     * @return the value of kGroup.group_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.group_name
     *
     * @param groupName the value for kGroup.group_name
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.start_date
     *
     * @return the value of kGroup.start_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.start_date
     *
     * @param startDate the value for kGroup.start_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setStartDate(Integer startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.end_date
     *
     * @return the value of kGroup.end_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Integer getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.end_date
     *
     * @param endDate the value for kGroup.end_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setEndDate(Integer endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.reportType
     *
     * @return the value of kGroup.reportType
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getReportType() {
        return reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.reportType
     *
     * @param reportType the value for kGroup.reportType
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.reg_date
     *
     * @return the value of kGroup.reg_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.reg_date
     *
     * @param regDate the value for kGroup.reg_date
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kGroup.reportItem
     *
     * @return the value of kGroup.reportItem
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public String getReportItem() {
        return reportItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kGroup.reportItem
     *
     * @param reportItem the value for kGroup.reportItem
     *
     * @mbg.generated Wed Dec 21 14:44:49 KST 2016
     */
    public void setReportItem(String reportItem) {
        this.reportItem = reportItem;
    }
}