package org.ohjic.mem.model;

public class ManagerWithBLOBs extends Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.comment
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.config
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    private String config;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.comment
     *
     * @return the value of manager.comment
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.comment
     *
     * @param comment the value for manager.comment
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.config
     *
     * @return the value of manager.config
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.config
     *
     * @param config the value for manager.config
     *
     * @mbg.generated Thu Jan 05 09:30:18 KST 2017
     */
    public void setConfig(String config) {
        this.config = config;
    }
}