package org.ohjic.mem.model;

import java.util.Date;

public class Member extends Kyo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.fid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private byte[] grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.fam_leader
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String famLeader;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String relation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_name_distinct
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberNameDistinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_name_en
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberNameEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_name_han
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberNameHan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.rrn_id1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String rrnId1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.rrn_id2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String rrnId2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.birth_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Short birthYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.birth_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Short birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.birth_solar
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer birthSolar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_sex
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.blood_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String blood_type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_homepage
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberHomepage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_cellphone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberCellphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_email
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer pGrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String pGradeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date pGradeDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String pGradeMinister;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String pGradeChurch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.p_grade_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer pGradeOrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.guide
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String guide;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.guide2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String guide2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.guide_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String guidePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.guide_relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String guideRelation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.regi_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer regiDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.reception_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer receptionDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.wedding
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String wedding;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.wedding_anniversary
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String weddingAnniversary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer christening;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String christeningName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date christeningDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String christeningChurch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String christeningMinister;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.christening_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer christeningOrd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String lastChurch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String lastGrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_act
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String lastAct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_zipcode
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_address1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberAddress1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_address2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberAddress2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_address_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberAddressStreet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_zipcode_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String member_zipcodeStreet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.job
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String job;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.job_type_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String jobTypeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.job_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer jobType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.career_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String careerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.career
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer career;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.company_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String companyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.company_position
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String companyPosition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.company_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String companyPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String schoolType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String schoolName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer schoolYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer schoolGrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_major
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String schoolMajor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.school_class
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String schoolClass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.car_number
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String carNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.car_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String carType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.parking_permit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date parkingPermit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.member_image
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String memberImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.inputDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date inputDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.register_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String registerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.register_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String registerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_view
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer lastView;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.modifier_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String modifierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.modifier_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String modifierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc3
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc4
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc5
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc6
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc7
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc8
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.etc9
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String etc9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.removed
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private byte[] removed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cDepth1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer cDepth1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cDepth2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer cDepth2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cDepth1Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String cDepth1Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cDepth2Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String cDepth2Name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cGroupUpdateDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date cGroupUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_kgrouplog
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer lastKgrouplog;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.partner_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String partnerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.partner_tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer partnerTid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.parent_name1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String parentName1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.parent_phone1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String parentPhone1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.parent_name2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String parentName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.parent_phone2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String parentPhone2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.fid_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer fidBefore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.relation_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private String relationBefore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.last_visit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Date lastVisit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.with_family
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Byte withFamily;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.interest
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	private Integer interest;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.tid
	 * @return  the value of member.tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.tid
	 * @param tid  the value for member.tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.fid
	 * @return  the value of member.fid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.fid
	 * @param fid  the value for member.fid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setFid(Integer fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.grade
	 * @return  the value of member.grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public byte[] getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.grade
	 * @param grade  the value for member.grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setGrade(byte[] grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.fam_leader
	 * @return  the value of member.fam_leader
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getFamLeader() {
		return famLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.fam_leader
	 * @param famLeader  the value for member.fam_leader
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setFamLeader(String famLeader) {
		this.famLeader = famLeader;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.relation
	 * @return  the value of member.relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRelation() {
		return relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.relation
	 * @param relation  the value for member.relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRelation(String relation) {
		this.relation = relation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_name
	 * @return  the value of member.member_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_name
	 * @param memberName  the value for member.member_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_name_distinct
	 * @return  the value of member.member_name_distinct
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberNameDistinct() {
		return memberNameDistinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_name_distinct
	 * @param memberNameDistinct  the value for member.member_name_distinct
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberNameDistinct(String memberNameDistinct) {
		this.memberNameDistinct = memberNameDistinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_name_en
	 * @return  the value of member.member_name_en
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberNameEn() {
		return memberNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_name_en
	 * @param memberNameEn  the value for member.member_name_en
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberNameEn(String memberNameEn) {
		this.memberNameEn = memberNameEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_name_han
	 * @return  the value of member.member_name_han
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberNameHan() {
		return memberNameHan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_name_han
	 * @param memberNameHan  the value for member.member_name_han
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberNameHan(String memberNameHan) {
		this.memberNameHan = memberNameHan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.rrn_id1
	 * @return  the value of member.rrn_id1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRrnId1() {
		return rrnId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.rrn_id1
	 * @param rrnId1  the value for member.rrn_id1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRrnId1(String rrnId1) {
		this.rrnId1 = rrnId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.rrn_id2
	 * @return  the value of member.rrn_id2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRrnId2() {
		return rrnId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.rrn_id2
	 * @param rrnId2  the value for member.rrn_id2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRrnId2(String rrnId2) {
		this.rrnId2 = rrnId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.birth_year
	 * @return  the value of member.birth_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Short getBirthYear() {
		return birthYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.birth_year
	 * @param birthYear  the value for member.birth_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setBirthYear(Short birthYear) {
		this.birthYear = birthYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.birth_date
	 * @return  the value of member.birth_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Short getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.birth_date
	 * @param birthDate  the value for member.birth_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setBirthDate(Short birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.birth_solar
	 * @return  the value of member.birth_solar
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getBirthSolar() {
		return birthSolar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.birth_solar
	 * @param birthSolar  the value for member.birth_solar
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setBirthSolar(Integer birthSolar) {
		this.birthSolar = birthSolar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_sex
	 * @return  the value of member.member_sex
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberSex() {
		return memberSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_sex
	 * @param memberSex  the value for member.member_sex
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberSex(String memberSex) {
		this.memberSex = memberSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.blood_type
	 * @return  the value of member.blood_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getBlood_type() {
		return blood_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.blood_type
	 * @param blood_type  the value for member.blood_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setBlood_type(String blood_type) {
		this.blood_type = blood_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_homepage
	 * @return  the value of member.member_homepage
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberHomepage() {
		return memberHomepage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_homepage
	 * @param memberHomepage  the value for member.member_homepage
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberHomepage(String memberHomepage) {
		this.memberHomepage = memberHomepage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_phone
	 * @return  the value of member.member_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberPhone() {
		return memberPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_phone
	 * @param memberPhone  the value for member.member_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberPhone(String memberPhone) {
		this.memberPhone = memberPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_cellphone
	 * @return  the value of member.member_cellphone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberCellphone() {
		return memberCellphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_cellphone
	 * @param memberCellphone  the value for member.member_cellphone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberCellphone(String memberCellphone) {
		this.memberCellphone = memberCellphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_email
	 * @return  the value of member.member_email
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberEmail() {
		return memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_email
	 * @param memberEmail  the value for member.member_email
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade
	 * @return  the value of member.p_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getpGrade() {
		return pGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade
	 * @param pGrade  the value for member.p_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGrade(Integer pGrade) {
		this.pGrade = pGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade_name
	 * @return  the value of member.p_grade_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getpGradeName() {
		return pGradeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade_name
	 * @param pGradeName  the value for member.p_grade_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGradeName(String pGradeName) {
		this.pGradeName = pGradeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade_date
	 * @return  the value of member.p_grade_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getpGradeDate() {
		return pGradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade_date
	 * @param pGradeDate  the value for member.p_grade_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGradeDate(Date pGradeDate) {
		this.pGradeDate = pGradeDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade_minister
	 * @return  the value of member.p_grade_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getpGradeMinister() {
		return pGradeMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade_minister
	 * @param pGradeMinister  the value for member.p_grade_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGradeMinister(String pGradeMinister) {
		this.pGradeMinister = pGradeMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade_church
	 * @return  the value of member.p_grade_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getpGradeChurch() {
		return pGradeChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade_church
	 * @param pGradeChurch  the value for member.p_grade_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGradeChurch(String pGradeChurch) {
		this.pGradeChurch = pGradeChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.p_grade_ord
	 * @return  the value of member.p_grade_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getpGradeOrd() {
		return pGradeOrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.p_grade_ord
	 * @param pGradeOrd  the value for member.p_grade_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setpGradeOrd(Integer pGradeOrd) {
		this.pGradeOrd = pGradeOrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.guide
	 * @return  the value of member.guide
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getGuide() {
		return guide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.guide
	 * @param guide  the value for member.guide
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setGuide(String guide) {
		this.guide = guide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.guide2
	 * @return  the value of member.guide2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getGuide2() {
		return guide2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.guide2
	 * @param guide2  the value for member.guide2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setGuide2(String guide2) {
		this.guide2 = guide2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.guide_phone
	 * @return  the value of member.guide_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getGuidePhone() {
		return guidePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.guide_phone
	 * @param guidePhone  the value for member.guide_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setGuidePhone(String guidePhone) {
		this.guidePhone = guidePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.guide_relation
	 * @return  the value of member.guide_relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getGuideRelation() {
		return guideRelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.guide_relation
	 * @param guideRelation  the value for member.guide_relation
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setGuideRelation(String guideRelation) {
		this.guideRelation = guideRelation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.regi_date
	 * @return  the value of member.regi_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getRegiDate() {
		return regiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.regi_date
	 * @param regiDate  the value for member.regi_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRegiDate(Integer regiDate) {
		this.regiDate = regiDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.reception_date
	 * @return  the value of member.reception_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getReceptionDate() {
		return receptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.reception_date
	 * @param receptionDate  the value for member.reception_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setReceptionDate(Integer receptionDate) {
		this.receptionDate = receptionDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.wedding
	 * @return  the value of member.wedding
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getWedding() {
		return wedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.wedding
	 * @param wedding  the value for member.wedding
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setWedding(String wedding) {
		this.wedding = wedding;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.wedding_anniversary
	 * @return  the value of member.wedding_anniversary
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getWeddingAnniversary() {
		return weddingAnniversary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.wedding_anniversary
	 * @param weddingAnniversary  the value for member.wedding_anniversary
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setWeddingAnniversary(String weddingAnniversary) {
		this.weddingAnniversary = weddingAnniversary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening
	 * @return  the value of member.christening
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getChristening() {
		return christening;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening
	 * @param christening  the value for member.christening
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristening(Integer christening) {
		this.christening = christening;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening_name
	 * @return  the value of member.christening_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getChristeningName() {
		return christeningName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening_name
	 * @param christeningName  the value for member.christening_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristeningName(String christeningName) {
		this.christeningName = christeningName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening_date
	 * @return  the value of member.christening_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getChristeningDate() {
		return christeningDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening_date
	 * @param christeningDate  the value for member.christening_date
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristeningDate(Date christeningDate) {
		this.christeningDate = christeningDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening_church
	 * @return  the value of member.christening_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getChristeningChurch() {
		return christeningChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening_church
	 * @param christeningChurch  the value for member.christening_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristeningChurch(String christeningChurch) {
		this.christeningChurch = christeningChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening_minister
	 * @return  the value of member.christening_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getChristeningMinister() {
		return christeningMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening_minister
	 * @param christeningMinister  the value for member.christening_minister
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristeningMinister(String christeningMinister) {
		this.christeningMinister = christeningMinister;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.christening_ord
	 * @return  the value of member.christening_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getChristeningOrd() {
		return christeningOrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.christening_ord
	 * @param christeningOrd  the value for member.christening_ord
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setChristeningOrd(Integer christeningOrd) {
		this.christeningOrd = christeningOrd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_church
	 * @return  the value of member.last_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getLastChurch() {
		return lastChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_church
	 * @param lastChurch  the value for member.last_church
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastChurch(String lastChurch) {
		this.lastChurch = lastChurch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_grade
	 * @return  the value of member.last_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getLastGrade() {
		return lastGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_grade
	 * @param lastGrade  the value for member.last_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastGrade(String lastGrade) {
		this.lastGrade = lastGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_act
	 * @return  the value of member.last_act
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getLastAct() {
		return lastAct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_act
	 * @param lastAct  the value for member.last_act
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastAct(String lastAct) {
		this.lastAct = lastAct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_zipcode
	 * @return  the value of member.member_zipcode
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberZipcode() {
		return memberZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_zipcode
	 * @param memberZipcode  the value for member.member_zipcode
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberZipcode(String memberZipcode) {
		this.memberZipcode = memberZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_address1
	 * @return  the value of member.member_address1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberAddress1() {
		return memberAddress1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_address1
	 * @param memberAddress1  the value for member.member_address1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberAddress1(String memberAddress1) {
		this.memberAddress1 = memberAddress1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_address2
	 * @return  the value of member.member_address2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberAddress2() {
		return memberAddress2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_address2
	 * @param memberAddress2  the value for member.member_address2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberAddress2(String memberAddress2) {
		this.memberAddress2 = memberAddress2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_address_street
	 * @return  the value of member.member_address_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberAddressStreet() {
		return memberAddressStreet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_address_street
	 * @param memberAddressStreet  the value for member.member_address_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberAddressStreet(String memberAddressStreet) {
		this.memberAddressStreet = memberAddressStreet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_zipcode_street
	 * @return  the value of member.member_zipcode_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMember_zipcodeStreet() {
		return member_zipcodeStreet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_zipcode_street
	 * @param member_zipcodeStreet  the value for member.member_zipcode_street
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMember_zipcodeStreet(String member_zipcodeStreet) {
		this.member_zipcodeStreet = member_zipcodeStreet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.job
	 * @return  the value of member.job
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.job
	 * @param job  the value for member.job
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.job_type_name
	 * @return  the value of member.job_type_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getJobTypeName() {
		return jobTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.job_type_name
	 * @param jobTypeName  the value for member.job_type_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setJobTypeName(String jobTypeName) {
		this.jobTypeName = jobTypeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.job_type
	 * @return  the value of member.job_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getJobType() {
		return jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.job_type
	 * @param jobType  the value for member.job_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setJobType(Integer jobType) {
		this.jobType = jobType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.career_name
	 * @return  the value of member.career_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCareerName() {
		return careerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.career_name
	 * @param careerName  the value for member.career_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCareerName(String careerName) {
		this.careerName = careerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.career
	 * @return  the value of member.career
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getCareer() {
		return career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.career
	 * @param career  the value for member.career
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCareer(Integer career) {
		this.career = career;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.company_name
	 * @return  the value of member.company_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.company_name
	 * @param companyName  the value for member.company_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.company_position
	 * @return  the value of member.company_position
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCompanyPosition() {
		return companyPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.company_position
	 * @param companyPosition  the value for member.company_position
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCompanyPosition(String companyPosition) {
		this.companyPosition = companyPosition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.company_phone
	 * @return  the value of member.company_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCompanyPhone() {
		return companyPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.company_phone
	 * @param companyPhone  the value for member.company_phone
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCompanyPhone(String companyPhone) {
		this.companyPhone = companyPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_type
	 * @return  the value of member.school_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getSchoolType() {
		return schoolType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_type
	 * @param schoolType  the value for member.school_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolType(String schoolType) {
		this.schoolType = schoolType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_name
	 * @return  the value of member.school_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getSchoolName() {
		return schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_name
	 * @param schoolName  the value for member.school_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_year
	 * @return  the value of member.school_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getSchoolYear() {
		return schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_year
	 * @param schoolYear  the value for member.school_year
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolYear(Integer schoolYear) {
		this.schoolYear = schoolYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_grade
	 * @return  the value of member.school_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getSchoolGrade() {
		return schoolGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_grade
	 * @param schoolGrade  the value for member.school_grade
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolGrade(Integer schoolGrade) {
		this.schoolGrade = schoolGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_major
	 * @return  the value of member.school_major
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getSchoolMajor() {
		return schoolMajor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_major
	 * @param schoolMajor  the value for member.school_major
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolMajor(String schoolMajor) {
		this.schoolMajor = schoolMajor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.school_class
	 * @return  the value of member.school_class
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getSchoolClass() {
		return schoolClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.school_class
	 * @param schoolClass  the value for member.school_class
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setSchoolClass(String schoolClass) {
		this.schoolClass = schoolClass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.car_number
	 * @return  the value of member.car_number
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCarNumber() {
		return carNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.car_number
	 * @param carNumber  the value for member.car_number
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCarNumber(String carNumber) {
		this.carNumber = carNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.car_type
	 * @return  the value of member.car_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getCarType() {
		return carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.car_type
	 * @param carType  the value for member.car_type
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setCarType(String carType) {
		this.carType = carType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.parking_permit
	 * @return  the value of member.parking_permit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getParkingPermit() {
		return parkingPermit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.parking_permit
	 * @param parkingPermit  the value for member.parking_permit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setParkingPermit(Date parkingPermit) {
		this.parkingPermit = parkingPermit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.member_image
	 * @return  the value of member.member_image
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getMemberImage() {
		return memberImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.member_image
	 * @param memberImage  the value for member.member_image
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setMemberImage(String memberImage) {
		this.memberImage = memberImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.inputDate
	 * @return  the value of member.inputDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getInputDate() {
		return inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.inputDate
	 * @param inputDate  the value for member.inputDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.register_id
	 * @return  the value of member.register_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRegisterId() {
		return registerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.register_id
	 * @param registerId  the value for member.register_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRegisterId(String registerId) {
		this.registerId = registerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.register_name
	 * @return  the value of member.register_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRegisterName() {
		return registerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.register_name
	 * @param registerName  the value for member.register_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRegisterName(String registerName) {
		this.registerName = registerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_view
	 * @return  the value of member.last_view
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getLastView() {
		return lastView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_view
	 * @param lastView  the value for member.last_view
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastView(Integer lastView) {
		this.lastView = lastView;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.modifier_id
	 * @return  the value of member.modifier_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getModifierId() {
		return modifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.modifier_id
	 * @param modifierId  the value for member.modifier_id
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setModifierId(String modifierId) {
		this.modifierId = modifierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.modifier_name
	 * @return  the value of member.modifier_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getModifierName() {
		return modifierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.modifier_name
	 * @param modifierName  the value for member.modifier_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setModifierName(String modifierName) {
		this.modifierName = modifierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc1
	 * @return  the value of member.etc1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc1() {
		return etc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc1
	 * @param etc1  the value for member.etc1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc1(String etc1) {
		this.etc1 = etc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc2
	 * @return  the value of member.etc2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc2() {
		return etc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc2
	 * @param etc2  the value for member.etc2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc2(String etc2) {
		this.etc2 = etc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc3
	 * @return  the value of member.etc3
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc3() {
		return etc3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc3
	 * @param etc3  the value for member.etc3
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc3(String etc3) {
		this.etc3 = etc3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc4
	 * @return  the value of member.etc4
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc4() {
		return etc4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc4
	 * @param etc4  the value for member.etc4
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc4(String etc4) {
		this.etc4 = etc4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc5
	 * @return  the value of member.etc5
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc5() {
		return etc5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc5
	 * @param etc5  the value for member.etc5
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc5(String etc5) {
		this.etc5 = etc5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc6
	 * @return  the value of member.etc6
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc6() {
		return etc6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc6
	 * @param etc6  the value for member.etc6
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc6(String etc6) {
		this.etc6 = etc6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc7
	 * @return  the value of member.etc7
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc7() {
		return etc7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc7
	 * @param etc7  the value for member.etc7
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc7(String etc7) {
		this.etc7 = etc7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc8
	 * @return  the value of member.etc8
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc8() {
		return etc8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc8
	 * @param etc8  the value for member.etc8
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc8(String etc8) {
		this.etc8 = etc8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.etc9
	 * @return  the value of member.etc9
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getEtc9() {
		return etc9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.etc9
	 * @param etc9  the value for member.etc9
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setEtc9(String etc9) {
		this.etc9 = etc9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.removed
	 * @return  the value of member.removed
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public byte[] getRemoved() {
		return removed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.removed
	 * @param removed  the value for member.removed
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRemoved(byte[] removed) {
		this.removed = removed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cDepth1
	 * @return  the value of member.cDepth1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getcDepth1() {
		return cDepth1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cDepth1
	 * @param cDepth1  the value for member.cDepth1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setcDepth1(Integer cDepth1) {
		this.cDepth1 = cDepth1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cDepth2
	 * @return  the value of member.cDepth2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getcDepth2() {
		return cDepth2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cDepth2
	 * @param cDepth2  the value for member.cDepth2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setcDepth2(Integer cDepth2) {
		this.cDepth2 = cDepth2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cDepth1Name
	 * @return  the value of member.cDepth1Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getcDepth1Name() {
		return cDepth1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cDepth1Name
	 * @param cDepth1Name  the value for member.cDepth1Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setcDepth1Name(String cDepth1Name) {
		this.cDepth1Name = cDepth1Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cDepth2Name
	 * @return  the value of member.cDepth2Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getcDepth2Name() {
		return cDepth2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cDepth2Name
	 * @param cDepth2Name  the value for member.cDepth2Name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setcDepth2Name(String cDepth2Name) {
		this.cDepth2Name = cDepth2Name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cGroupUpdateDate
	 * @return  the value of member.cGroupUpdateDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getcGroupUpdateDate() {
		return cGroupUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cGroupUpdateDate
	 * @param cGroupUpdateDate  the value for member.cGroupUpdateDate
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setcGroupUpdateDate(Date cGroupUpdateDate) {
		this.cGroupUpdateDate = cGroupUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_kgrouplog
	 * @return  the value of member.last_kgrouplog
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getLastKgrouplog() {
		return lastKgrouplog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_kgrouplog
	 * @param lastKgrouplog  the value for member.last_kgrouplog
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastKgrouplog(Integer lastKgrouplog) {
		this.lastKgrouplog = lastKgrouplog;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.partner_name
	 * @return  the value of member.partner_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getPartnerName() {
		return partnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.partner_name
	 * @param partnerName  the value for member.partner_name
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.partner_tid
	 * @return  the value of member.partner_tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getPartnerTid() {
		return partnerTid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.partner_tid
	 * @param partnerTid  the value for member.partner_tid
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setPartnerTid(Integer partnerTid) {
		this.partnerTid = partnerTid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.parent_name1
	 * @return  the value of member.parent_name1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getParentName1() {
		return parentName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.parent_name1
	 * @param parentName1  the value for member.parent_name1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setParentName1(String parentName1) {
		this.parentName1 = parentName1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.parent_phone1
	 * @return  the value of member.parent_phone1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getParentPhone1() {
		return parentPhone1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.parent_phone1
	 * @param parentPhone1  the value for member.parent_phone1
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setParentPhone1(String parentPhone1) {
		this.parentPhone1 = parentPhone1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.parent_name2
	 * @return  the value of member.parent_name2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getParentName2() {
		return parentName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.parent_name2
	 * @param parentName2  the value for member.parent_name2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setParentName2(String parentName2) {
		this.parentName2 = parentName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.parent_phone2
	 * @return  the value of member.parent_phone2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getParentPhone2() {
		return parentPhone2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.parent_phone2
	 * @param parentPhone2  the value for member.parent_phone2
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setParentPhone2(String parentPhone2) {
		this.parentPhone2 = parentPhone2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.fid_before
	 * @return  the value of member.fid_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getFidBefore() {
		return fidBefore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.fid_before
	 * @param fidBefore  the value for member.fid_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setFidBefore(Integer fidBefore) {
		this.fidBefore = fidBefore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.relation_before
	 * @return  the value of member.relation_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public String getRelationBefore() {
		return relationBefore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.relation_before
	 * @param relationBefore  the value for member.relation_before
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setRelationBefore(String relationBefore) {
		this.relationBefore = relationBefore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.last_visit
	 * @return  the value of member.last_visit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Date getLastVisit() {
		return lastVisit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.last_visit
	 * @param lastVisit  the value for member.last_visit
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setLastVisit(Date lastVisit) {
		this.lastVisit = lastVisit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.with_family
	 * @return  the value of member.with_family
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Byte getWithFamily() {
		return withFamily;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.with_family
	 * @param withFamily  the value for member.with_family
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setWithFamily(Byte withFamily) {
		this.withFamily = withFamily;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.interest
	 * @return  the value of member.interest
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public Integer getInterest() {
		return interest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.interest
	 * @param interest  the value for member.interest
	 * @mbg.generated  Wed May 09 17:56:58 KST 2018
	 */
	public void setInterest(Integer interest) {
		this.interest = interest;
	}
}