package org.ohjic.mem.model;

import java.util.Date;

public class NextYearSettingStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.next_year_setting_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Integer nextYearSettingIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.church_code
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Integer churchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.year
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.k_part_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Integer kPartIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.status
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.manager_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Integer managerIdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.update_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column next_year_setting_status.reg_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    private Date regDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.next_year_setting_idx
     *
     * @return the value of next_year_setting_status.next_year_setting_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Integer getNextYearSettingIdx() {
        return nextYearSettingIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.next_year_setting_idx
     *
     * @param nextYearSettingIdx the value for next_year_setting_status.next_year_setting_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setNextYearSettingIdx(Integer nextYearSettingIdx) {
        this.nextYearSettingIdx = nextYearSettingIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.church_code
     *
     * @return the value of next_year_setting_status.church_code
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Integer getChurchCode() {
        return churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.church_code
     *
     * @param churchCode the value for next_year_setting_status.church_code
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setChurchCode(Integer churchCode) {
        this.churchCode = churchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.year
     *
     * @return the value of next_year_setting_status.year
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.year
     *
     * @param year the value for next_year_setting_status.year
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.k_part_idx
     *
     * @return the value of next_year_setting_status.k_part_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Integer getkPartIdx() {
        return kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.k_part_idx
     *
     * @param kPartIdx the value for next_year_setting_status.k_part_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setkPartIdx(Integer kPartIdx) {
        this.kPartIdx = kPartIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.status
     *
     * @return the value of next_year_setting_status.status
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.status
     *
     * @param status the value for next_year_setting_status.status
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.manager_idx
     *
     * @return the value of next_year_setting_status.manager_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Integer getManagerIdx() {
        return managerIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.manager_idx
     *
     * @param managerIdx the value for next_year_setting_status.manager_idx
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setManagerIdx(Integer managerIdx) {
        this.managerIdx = managerIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.update_date
     *
     * @return the value of next_year_setting_status.update_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.update_date
     *
     * @param updateDate the value for next_year_setting_status.update_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column next_year_setting_status.reg_date
     *
     * @return the value of next_year_setting_status.reg_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column next_year_setting_status.reg_date
     *
     * @param regDate the value for next_year_setting_status.reg_date
     *
     * @mbg.generated Mon Dec 26 14:30:37 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
    
    public String getkPartName() {
		return kPartName;
	}

	public void setkPartName(String kPartName) {
		this.kPartName = kPartName;
	}

	private String kPartName;
}