package com.medi.hs.dao;

import com.medi.hs.model.HanwhatotresscDocv;

public interface HanwhatotresscDocvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTRESSC_DOCV
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insert(HanwhatotresscDocv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTRESSC_DOCV
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insertSelective(HanwhatotresscDocv record);
}