package com.medi.hs.dao;

import com.medi.hs.model.Hanwha2chasc;

public interface Hanwha2chascMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHA2CHASC
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insert(Hanwha2chasc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHA2CHASC
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insertSelective(Hanwha2chasc record);
}