package com.medi.hs.dao;

import com.medi.hs.model.HanwhacancerscNewWithBLOBs;

public interface HanwhacancerscNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHACANCERSC_NEW
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insert(HanwhacancerscNewWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHACANCERSC_NEW
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insertSelective(HanwhacancerscNewWithBLOBs record);
}