package com.medi.hs.dao;

import com.medi.hs.model.HanwhatotalscGk;
import com.medi.hs.model.HanwhatotalscGkKey;

public interface HanwhatotalscGkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int deleteByPrimaryKey(HanwhatotalscGkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insert(HanwhatotalscGk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int insertSelective(HanwhatotalscGk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    HanwhatotalscGk selectByPrimaryKey(HanwhatotalscGkKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int updateByPrimaryKeySelective(HanwhatotalscGk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.HANWHATOTALSC_GK
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    int updateByPrimaryKey(HanwhatotalscGk record);
}