package com.medi.hs.dao;

import com.medi.hs.model.HsLabb42;

public interface HsLabb42Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	int deleteByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	int insert(HsLabb42 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	int insertSelective(HsLabb42 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	HsLabb42 selectByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	int updateByPrimaryKeySelective(HsLabb42 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table MEDI.HS_LABB42
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	int updateByPrimaryKey(HsLabb42 record);
}