package com.medi.hs.dao;

import com.medi.hs.model.MobilPersonal;

public interface MobilPersonalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.MOBIL_PERSONAL
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int insert(MobilPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.MOBIL_PERSONAL
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int insertSelective(MobilPersonal record);
}