package com.medi.hs.dao;

import com.medi.hs.model.Webregistpatient;

public interface WebregistpatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int deleteByPrimaryKey(String registWebPatientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int insert(Webregistpatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int insertSelective(Webregistpatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    Webregistpatient selectByPrimaryKey(String registWebPatientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int updateByPrimaryKeySelective(Webregistpatient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE.WEBREGISTPATIENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    int updateByPrimaryKey(Webregistpatient record);
}