package com.medi.hs.model;

public class HanwhatotalscGkKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC_GK.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC_GK.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC_GK.JUBGGUMKD
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String jubggumkd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC_GK.ID
     *
     * @return the value of MOBILE.HANWHATOTALSC_GK.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC_GK.ID
     *
     * @param id the value for MOBILE.HANWHATOTALSC_GK.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC_GK.SDATE
     *
     * @return the value of MOBILE.HANWHATOTALSC_GK.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC_GK.SDATE
     *
     * @param sdate the value for MOBILE.HANWHATOTALSC_GK.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC_GK.JUBGGUMKD
     *
     * @return the value of MOBILE.HANWHATOTALSC_GK.JUBGGUMKD
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getJubggumkd() {
        return jubggumkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC_GK.JUBGGUMKD
     *
     * @param jubggumkd the value for MOBILE.HANWHATOTALSC_GK.JUBGGUMKD
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setJubggumkd(String jubggumkd) {
        this.jubggumkd = jubggumkd;
    }
}