package com.medi.hs.model;

import java.util.Date;

public class Hanwhatotalsc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String jubsjubno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.NAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.PHONE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.PCS
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String pcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.SEX
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.RESVRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String resvrsend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.PANORSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String panosen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.AMRSRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String amrsrsend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Date datInsert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTALSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String codInsert;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.ID
     *
     * @return the value of MOBILE.HANWHATOTALSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.ID
     *
     * @param id the value for MOBILE.HANWHATOTALSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.JUBSJUBNO
     *
     * @return the value of MOBILE.HANWHATOTALSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getJubsjubno() {
        return jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.JUBSJUBNO
     *
     * @param jubsjubno the value for MOBILE.HANWHATOTALSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setJubsjubno(String jubsjubno) {
        this.jubsjubno = jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.SDATE
     *
     * @return the value of MOBILE.HANWHATOTALSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.SDATE
     *
     * @param sdate the value for MOBILE.HANWHATOTALSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.NO
     *
     * @return the value of MOBILE.HANWHATOTALSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.NO
     *
     * @param no the value for MOBILE.HANWHATOTALSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setNo(Short no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.NAME
     *
     * @return the value of MOBILE.HANWHATOTALSC.NAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.NAME
     *
     * @param name the value for MOBILE.HANWHATOTALSC.NAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.PHONE
     *
     * @return the value of MOBILE.HANWHATOTALSC.PHONE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.PHONE
     *
     * @param phone the value for MOBILE.HANWHATOTALSC.PHONE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.PCS
     *
     * @return the value of MOBILE.HANWHATOTALSC.PCS
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getPcs() {
        return pcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.PCS
     *
     * @param pcs the value for MOBILE.HANWHATOTALSC.PCS
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setPcs(String pcs) {
        this.pcs = pcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.BIRTHDAY
     *
     * @return the value of MOBILE.HANWHATOTALSC.BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.BIRTHDAY
     *
     * @param birthday the value for MOBILE.HANWHATOTALSC.BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.SEX
     *
     * @return the value of MOBILE.HANWHATOTALSC.SEX
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.SEX
     *
     * @param sex the value for MOBILE.HANWHATOTALSC.SEX
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.RESVRSEND
     *
     * @return the value of MOBILE.HANWHATOTALSC.RESVRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getResvrsend() {
        return resvrsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.RESVRSEND
     *
     * @param resvrsend the value for MOBILE.HANWHATOTALSC.RESVRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setResvrsend(String resvrsend) {
        this.resvrsend = resvrsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.PANORSEND
     *
     * @return the value of MOBILE.HANWHATOTALSC.PANORSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getPanosen() {
        return panosen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.PANORSEND
     *
     * @param panosen the value for MOBILE.HANWHATOTALSC.PANORSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setPanosen(String panosen) {
        this.panosen = panosen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.AMRSRSEND
     *
     * @return the value of MOBILE.HANWHATOTALSC.AMRSRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getAmrsrsend() {
        return amrsrsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.AMRSRSEND
     *
     * @param amrsrsend the value for MOBILE.HANWHATOTALSC.AMRSRSEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setAmrsrsend(String amrsrsend) {
        this.amrsrsend = amrsrsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.DAT_INSERT
     *
     * @return the value of MOBILE.HANWHATOTALSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Date getDatInsert() {
        return datInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.DAT_INSERT
     *
     * @param datInsert the value for MOBILE.HANWHATOTALSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDatInsert(Date datInsert) {
        this.datInsert = datInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTALSC.COD_INSERT
     *
     * @return the value of MOBILE.HANWHATOTALSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getCodInsert() {
        return codInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTALSC.COD_INSERT
     *
     * @param codInsert the value for MOBILE.HANWHATOTALSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setCodInsert(String codInsert) {
        this.codInsert = codInsert;
    }
}