package com.medi.hs.model;

public class HanwhatotresscKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.ID
     *
     * @return the value of MOBILE.HANWHATOTRESSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.ID
     *
     * @param id the value for MOBILE.HANWHATOTRESSC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.SDATE
     *
     * @return the value of MOBILE.HANWHATOTRESSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.SDATE
     *
     * @param sdate the value for MOBILE.HANWHATOTRESSC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.CODE
     *
     * @return the value of MOBILE.HANWHATOTRESSC.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.CODE
     *
     * @param code the value for MOBILE.HANWHATOTRESSC.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }
}