package com.medi.hs.model;

public class Hanwha2chasc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String jubsjubno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO_GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sGulkwa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO6_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so6_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO7_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so7_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.INJI_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String injiPan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.TOT_INJI
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String totInji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO8_40
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so8_40;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO8_40_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so8_40_score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO8_661
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so8_661;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO8_66A_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so866aScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so1_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so1_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SMOKE_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String smokeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so2_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so2_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.DRINK_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String drinkScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so3_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so3_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO3_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so3_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO3_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so3_4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SPORT_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sporScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_1_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_1_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_1_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_1_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_2_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_2_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_2_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_3_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_3_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO4_2_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so4_2_4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.FOOD_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String foodScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_11
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_5
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_6
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_7
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_8
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHA2CHASC.SO5_8_MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String so5_8_memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.ID
     *
     * @return the value of MOBILE.HANWHA2CHASC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.ID
     *
     * @param id the value for MOBILE.HANWHA2CHASC.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.JUBSJUBNO
     *
     * @return the value of MOBILE.HANWHA2CHASC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getJubsjubno() {
        return jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.JUBSJUBNO
     *
     * @param jubsjubno the value for MOBILE.HANWHA2CHASC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setJubsjubno(String jubsjubno) {
        this.jubsjubno = jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SDATE
     *
     * @return the value of MOBILE.HANWHA2CHASC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SDATE
     *
     * @param sdate the value for MOBILE.HANWHA2CHASC.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO_GULKWA
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO_GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getsGulkwa() {
        return sGulkwa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO_GULKWA
     *
     * @param sGulkwa the value for MOBILE.HANWHA2CHASC.SO_GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setsGulkwa(String sGulkwa) {
        this.sGulkwa = sGulkwa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO6_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO6_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo6_1() {
        return so6_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO6_1
     *
     * @param so6_1 the value for MOBILE.HANWHA2CHASC.SO6_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo6_1(String so6_1) {
        this.so6_1 = so6_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO7_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO7_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo7_1() {
        return so7_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO7_1
     *
     * @param so7_1 the value for MOBILE.HANWHA2CHASC.SO7_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo7_1(String so7_1) {
        this.so7_1 = so7_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.INJI_PAN
     *
     * @return the value of MOBILE.HANWHA2CHASC.INJI_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getInjiPan() {
        return injiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.INJI_PAN
     *
     * @param injiPan the value for MOBILE.HANWHA2CHASC.INJI_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setInjiPan(String injiPan) {
        this.injiPan = injiPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.TOT_INJI
     *
     * @return the value of MOBILE.HANWHA2CHASC.TOT_INJI
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getTotInji() {
        return totInji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.TOT_INJI
     *
     * @param totInji the value for MOBILE.HANWHA2CHASC.TOT_INJI
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setTotInji(String totInji) {
        this.totInji = totInji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO8_40
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO8_40
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo8_40() {
        return so8_40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO8_40
     *
     * @param so8_40 the value for MOBILE.HANWHA2CHASC.SO8_40
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo8_40(String so8_40) {
        this.so8_40 = so8_40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO8_40_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO8_40_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo8_40_score() {
        return so8_40_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO8_40_SCORE
     *
     * @param so8_40_score the value for MOBILE.HANWHA2CHASC.SO8_40_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo8_40_score(String so8_40_score) {
        this.so8_40_score = so8_40_score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO8_661
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO8_661
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo8_661() {
        return so8_661;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO8_661
     *
     * @param so8_661 the value for MOBILE.HANWHA2CHASC.SO8_661
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo8_661(String so8_661) {
        this.so8_661 = so8_661;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO8_66A_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO8_66A_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo866aScore() {
        return so866aScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO8_66A_SCORE
     *
     * @param so866aScore the value for MOBILE.HANWHA2CHASC.SO8_66A_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo866aScore(String so866aScore) {
        this.so866aScore = so866aScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO1_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo1_1() {
        return so1_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO1_1
     *
     * @param so1_1 the value for MOBILE.HANWHA2CHASC.SO1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo1_1(String so1_1) {
        this.so1_1 = so1_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO1_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo1_2() {
        return so1_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO1_2
     *
     * @param so1_2 the value for MOBILE.HANWHA2CHASC.SO1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo1_2(String so1_2) {
        this.so1_2 = so1_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SMOKE_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.SMOKE_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSmokeScore() {
        return smokeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SMOKE_SCORE
     *
     * @param smokeScore the value for MOBILE.HANWHA2CHASC.SMOKE_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSmokeScore(String smokeScore) {
        this.smokeScore = smokeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO2_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo2_1() {
        return so2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO2_1
     *
     * @param so2_1 the value for MOBILE.HANWHA2CHASC.SO2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo2_1(String so2_1) {
        this.so2_1 = so2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO2_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo2_2() {
        return so2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO2_2
     *
     * @param so2_2 the value for MOBILE.HANWHA2CHASC.SO2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo2_2(String so2_2) {
        this.so2_2 = so2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.DRINK_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.DRINK_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDrinkScore() {
        return drinkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.DRINK_SCORE
     *
     * @param drinkScore the value for MOBILE.HANWHA2CHASC.DRINK_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDrinkScore(String drinkScore) {
        this.drinkScore = drinkScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO3_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo3_1() {
        return so3_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO3_1
     *
     * @param so3_1 the value for MOBILE.HANWHA2CHASC.SO3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo3_1(String so3_1) {
        this.so3_1 = so3_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO3_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo3_2() {
        return so3_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO3_2
     *
     * @param so3_2 the value for MOBILE.HANWHA2CHASC.SO3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo3_2(String so3_2) {
        this.so3_2 = so3_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO3_3
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO3_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo3_3() {
        return so3_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO3_3
     *
     * @param so3_3 the value for MOBILE.HANWHA2CHASC.SO3_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo3_3(String so3_3) {
        this.so3_3 = so3_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO3_4
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO3_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo3_4() {
        return so3_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO3_4
     *
     * @param so3_4 the value for MOBILE.HANWHA2CHASC.SO3_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo3_4(String so3_4) {
        this.so3_4 = so3_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SPORT_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.SPORT_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSporScore() {
        return sporScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SPORT_SCORE
     *
     * @param sporScore the value for MOBILE.HANWHA2CHASC.SPORT_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSporScore(String sporScore) {
        this.sporScore = sporScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_1() {
        return so4_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_1
     *
     * @param so4_1 the value for MOBILE.HANWHA2CHASC.SO4_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_1(String so4_1) {
        this.so4_1 = so4_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_1() {
        return so4_2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1
     *
     * @param so4_2_1 the value for MOBILE.HANWHA2CHASC.SO4_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_1(String so4_2_1) {
        this.so4_2_1 = so4_2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_1_1() {
        return so4_2_1_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_1
     *
     * @param so4_2_1_1 the value for MOBILE.HANWHA2CHASC.SO4_2_1_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_1_1(String so4_2_1_1) {
        this.so4_2_1_1 = so4_2_1_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_1_2() {
        return so4_2_1_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_2
     *
     * @param so4_2_1_2 the value for MOBILE.HANWHA2CHASC.SO4_2_1_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_1_2(String so4_2_1_2) {
        this.so4_2_1_2 = so4_2_1_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_3
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_1_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_1_3() {
        return so4_2_1_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_1_3
     *
     * @param so4_2_1_3 the value for MOBILE.HANWHA2CHASC.SO4_2_1_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_1_3(String so4_2_1_3) {
        this.so4_2_1_3 = so4_2_1_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_2() {
        return so4_2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2
     *
     * @param so4_2_2 the value for MOBILE.HANWHA2CHASC.SO4_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_2(String so4_2_2) {
        this.so4_2_2 = so4_2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_2_1() {
        return so4_2_2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_1
     *
     * @param so4_2_2_1 the value for MOBILE.HANWHA2CHASC.SO4_2_2_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_2_1(String so4_2_2_1) {
        this.so4_2_2_1 = so4_2_2_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_2_2() {
        return so4_2_2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_2
     *
     * @param so4_2_2_2 the value for MOBILE.HANWHA2CHASC.SO4_2_2_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_2_2(String so4_2_2_2) {
        this.so4_2_2_2 = so4_2_2_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_3
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_2_3() {
        return so4_2_2_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_2_3
     *
     * @param so4_2_2_3 the value for MOBILE.HANWHA2CHASC.SO4_2_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_2_3(String so4_2_2_3) {
        this.so4_2_2_3 = so4_2_2_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_3() {
        return so4_2_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3
     *
     * @param so4_2_3 the value for MOBILE.HANWHA2CHASC.SO4_2_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_3(String so4_2_3) {
        this.so4_2_3 = so4_2_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_3_1() {
        return so4_2_3_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3_1
     *
     * @param so4_2_3_1 the value for MOBILE.HANWHA2CHASC.SO4_2_3_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_3_1(String so4_2_3_1) {
        this.so4_2_3_1 = so4_2_3_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_3_2() {
        return so4_2_3_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_3_2
     *
     * @param so4_2_3_2 the value for MOBILE.HANWHA2CHASC.SO4_2_3_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_3_2(String so4_2_3_2) {
        this.so4_2_3_2 = so4_2_3_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO4_2_4
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO4_2_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo4_2_4() {
        return so4_2_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO4_2_4
     *
     * @param so4_2_4 the value for MOBILE.HANWHA2CHASC.SO4_2_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo4_2_4(String so4_2_4) {
        this.so4_2_4 = so4_2_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.FOOD_SCORE
     *
     * @return the value of MOBILE.HANWHA2CHASC.FOOD_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getFoodScore() {
        return foodScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.FOOD_SCORE
     *
     * @param foodScore the value for MOBILE.HANWHA2CHASC.FOOD_SCORE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setFoodScore(String foodScore) {
        this.foodScore = foodScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_1
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_1() {
        return so5_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_1
     *
     * @param so5_1 the value for MOBILE.HANWHA2CHASC.SO5_1
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_1(String so5_1) {
        this.so5_1 = so5_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_11
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_11
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_11() {
        return so5_11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_11
     *
     * @param so5_11 the value for MOBILE.HANWHA2CHASC.SO5_11
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_11(String so5_11) {
        this.so5_11 = so5_11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_2
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_2() {
        return so5_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_2
     *
     * @param so5_2 the value for MOBILE.HANWHA2CHASC.SO5_2
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_2(String so5_2) {
        this.so5_2 = so5_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_3
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_3() {
        return so5_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_3
     *
     * @param so5_3 the value for MOBILE.HANWHA2CHASC.SO5_3
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_3(String so5_3) {
        this.so5_3 = so5_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_4
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_4() {
        return so5_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_4
     *
     * @param so5_4 the value for MOBILE.HANWHA2CHASC.SO5_4
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_4(String so5_4) {
        this.so5_4 = so5_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_5
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_5
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_5() {
        return so5_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_5
     *
     * @param so5_5 the value for MOBILE.HANWHA2CHASC.SO5_5
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_5(String so5_5) {
        this.so5_5 = so5_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_6
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_6
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_6() {
        return so5_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_6
     *
     * @param so5_6 the value for MOBILE.HANWHA2CHASC.SO5_6
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_6(String so5_6) {
        this.so5_6 = so5_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_7
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_7
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_7() {
        return so5_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_7
     *
     * @param so5_7 the value for MOBILE.HANWHA2CHASC.SO5_7
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_7(String so5_7) {
        this.so5_7 = so5_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_8
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_8
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_8() {
        return so5_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_8
     *
     * @param so5_8 the value for MOBILE.HANWHA2CHASC.SO5_8
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_8(String so5_8) {
        this.so5_8 = so5_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHA2CHASC.SO5_8_MEMO
     *
     * @return the value of MOBILE.HANWHA2CHASC.SO5_8_MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSo5_8_memo() {
        return so5_8_memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHA2CHASC.SO5_8_MEMO
     *
     * @param so5_8_memo the value for MOBILE.HANWHA2CHASC.SO5_8_MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSo5_8_memo(String so5_8_memo) {
        this.so5_8_memo = so5_8_memo;
    }
}