package com.medi.hs.model;

public class HanwhacancerscNewWithBLOBs extends HanwhacancerscNew {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.RECOMMEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String gulkwa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.RECOMMEND
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.RECOMMEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.RECOMMEND
     *
     * @param recommend the value for MOBILE.HANWHACANCERSC_NEW.RECOMMEND
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.GULKWA
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getGulkwa() {
        return gulkwa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.GULKWA
     *
     * @param gulkwa the value for MOBILE.HANWHACANCERSC_NEW.GULKWA
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setGulkwa(String gulkwa) {
        this.gulkwa = gulkwa;
    }
}