package com.medi.hs.model;

import java.util.Date;

public class Hanwhatotressc extends HanwhatotresscKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String jubsjubno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.KNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String kname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.ENAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.SNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.VALUE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.DECISION
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String decision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.STYLE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String stype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.LOW_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String logMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.HIGH_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String highMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.LOW_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String lowWoman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.HIGH_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String highWoman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.REFCHAR
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String refchar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Date datInsert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String codInsert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHATOTRESSC.MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.JUBSJUBNO
     *
     * @return the value of MOBILE.HANWHATOTRESSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getJubsjubno() {
        return jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.JUBSJUBNO
     *
     * @param jubsjubno the value for MOBILE.HANWHATOTRESSC.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setJubsjubno(String jubsjubno) {
        this.jubsjubno = jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.NO
     *
     * @return the value of MOBILE.HANWHATOTRESSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.NO
     *
     * @param no the value for MOBILE.HANWHATOTRESSC.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setNo(Short no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.KNAME
     *
     * @return the value of MOBILE.HANWHATOTRESSC.KNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getKname() {
        return kname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.KNAME
     *
     * @param kname the value for MOBILE.HANWHATOTRESSC.KNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setKname(String kname) {
        this.kname = kname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.ENAME
     *
     * @return the value of MOBILE.HANWHATOTRESSC.ENAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.ENAME
     *
     * @param ename the value for MOBILE.HANWHATOTRESSC.ENAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.SNAME
     *
     * @return the value of MOBILE.HANWHATOTRESSC.SNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.SNAME
     *
     * @param sname the value for MOBILE.HANWHATOTRESSC.SNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.VALUE
     *
     * @return the value of MOBILE.HANWHATOTRESSC.VALUE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.VALUE
     *
     * @param value the value for MOBILE.HANWHATOTRESSC.VALUE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.DECISION
     *
     * @return the value of MOBILE.HANWHATOTRESSC.DECISION
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDecision() {
        return decision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.DECISION
     *
     * @param decision the value for MOBILE.HANWHATOTRESSC.DECISION
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDecision(String decision) {
        this.decision = decision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.STYLE
     *
     * @return the value of MOBILE.HANWHATOTRESSC.STYLE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getStype() {
        return stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.STYLE
     *
     * @param stype the value for MOBILE.HANWHATOTRESSC.STYLE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setStype(String stype) {
        this.stype = stype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.LOW_MAN
     *
     * @return the value of MOBILE.HANWHATOTRESSC.LOW_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getLogMan() {
        return logMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.LOW_MAN
     *
     * @param logMan the value for MOBILE.HANWHATOTRESSC.LOW_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setLogMan(String logMan) {
        this.logMan = logMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.HIGH_MAN
     *
     * @return the value of MOBILE.HANWHATOTRESSC.HIGH_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getHighMan() {
        return highMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.HIGH_MAN
     *
     * @param highMan the value for MOBILE.HANWHATOTRESSC.HIGH_MAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setHighMan(String highMan) {
        this.highMan = highMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.LOW_WOMAN
     *
     * @return the value of MOBILE.HANWHATOTRESSC.LOW_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getLowWoman() {
        return lowWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.LOW_WOMAN
     *
     * @param lowWoman the value for MOBILE.HANWHATOTRESSC.LOW_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setLowWoman(String lowWoman) {
        this.lowWoman = lowWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.HIGH_WOMAN
     *
     * @return the value of MOBILE.HANWHATOTRESSC.HIGH_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getHighWoman() {
        return highWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.HIGH_WOMAN
     *
     * @param highWoman the value for MOBILE.HANWHATOTRESSC.HIGH_WOMAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setHighWoman(String highWoman) {
        this.highWoman = highWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.REFCHAR
     *
     * @return the value of MOBILE.HANWHATOTRESSC.REFCHAR
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getRefchar() {
        return refchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.REFCHAR
     *
     * @param refchar the value for MOBILE.HANWHATOTRESSC.REFCHAR
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setRefchar(String refchar) {
        this.refchar = refchar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.DAT_INSERT
     *
     * @return the value of MOBILE.HANWHATOTRESSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Date getDatInsert() {
        return datInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.DAT_INSERT
     *
     * @param datInsert the value for MOBILE.HANWHATOTRESSC.DAT_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDatInsert(Date datInsert) {
        this.datInsert = datInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.COD_INSERT
     *
     * @return the value of MOBILE.HANWHATOTRESSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getCodInsert() {
        return codInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.COD_INSERT
     *
     * @param codInsert the value for MOBILE.HANWHATOTRESSC.COD_INSERT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setCodInsert(String codInsert) {
        this.codInsert = codInsert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHATOTRESSC.MEMO
     *
     * @return the value of MOBILE.HANWHATOTRESSC.MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHATOTRESSC.MEMO
     *
     * @param memo the value for MOBILE.HANWHATOTRESSC.MEMO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}