package com.medi.hs.model;

public class HanwhacancerscNew {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String jubsjubno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private Short no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.EXAM_NM
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String examNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.EXAM_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String examDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.EXAM_SO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String examSo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.EXAM_JJ
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String examJj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.EXAM_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String examPan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.PAN_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String panDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String doctorno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String doctorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.DESC_KIKWAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String descKikwan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.HANWHACANCERSC_NEW.DESC_HLBW
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    private String deschlbw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.ID
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.ID
     *
     * @param id the value for MOBILE.HANWHACANCERSC_NEW.ID
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.JUBSJUBNO
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getJubsjubno() {
        return jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.JUBSJUBNO
     *
     * @param jubsjubno the value for MOBILE.HANWHACANCERSC_NEW.JUBSJUBNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setJubsjubno(String jubsjubno) {
        this.jubsjubno = jubsjubno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.SDATE
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.SDATE
     *
     * @param sdate the value for MOBILE.HANWHACANCERSC_NEW.SDATE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.NO
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public Short getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.NO
     *
     * @param no the value for MOBILE.HANWHACANCERSC_NEW.NO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setNo(Short no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.CODE
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.CODE
     *
     * @param code the value for MOBILE.HANWHACANCERSC_NEW.CODE
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_NM
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.EXAM_NM
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getExamNm() {
        return examNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_NM
     *
     * @param examNm the value for MOBILE.HANWHACANCERSC_NEW.EXAM_NM
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setExamNm(String examNm) {
        this.examNm = examNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_DT
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.EXAM_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getExamDt() {
        return examDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_DT
     *
     * @param examDt the value for MOBILE.HANWHACANCERSC_NEW.EXAM_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setExamDt(String examDt) {
        this.examDt = examDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_SO
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.EXAM_SO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getExamSo() {
        return examSo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_SO
     *
     * @param examSo the value for MOBILE.HANWHACANCERSC_NEW.EXAM_SO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setExamSo(String examSo) {
        this.examSo = examSo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_JJ
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.EXAM_JJ
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getExamJj() {
        return examJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_JJ
     *
     * @param examJj the value for MOBILE.HANWHACANCERSC_NEW.EXAM_JJ
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setExamJj(String examJj) {
        this.examJj = examJj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_PAN
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.EXAM_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getExamPan() {
        return examPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.EXAM_PAN
     *
     * @param examPan the value for MOBILE.HANWHACANCERSC_NEW.EXAM_PAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setExamPan(String examPan) {
        this.examPan = examPan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.PAN_DT
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.PAN_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getPanDt() {
        return panDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.PAN_DT
     *
     * @param panDt the value for MOBILE.HANWHACANCERSC_NEW.PAN_DT
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setPanDt(String panDt) {
        this.panDt = panDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNO
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.DOCTORNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDoctorno() {
        return doctorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNO
     *
     * @param doctorno the value for MOBILE.HANWHACANCERSC_NEW.DOCTORNO
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDoctorno(String doctorno) {
        this.doctorno = doctorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNAME
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.DOCTORNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDoctorname() {
        return doctorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.DOCTORNAME
     *
     * @param doctorname the value for MOBILE.HANWHACANCERSC_NEW.DOCTORNAME
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.DESC_KIKWAN
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.DESC_KIKWAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDescKikwan() {
        return descKikwan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.DESC_KIKWAN
     *
     * @param descKikwan the value for MOBILE.HANWHACANCERSC_NEW.DESC_KIKWAN
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDescKikwan(String descKikwan) {
        this.descKikwan = descKikwan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.HANWHACANCERSC_NEW.DESC_HLBW
     *
     * @return the value of MOBILE.HANWHACANCERSC_NEW.DESC_HLBW
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public String getDeschlbw() {
        return deschlbw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.HANWHACANCERSC_NEW.DESC_HLBW
     *
     * @param deschlbw the value for MOBILE.HANWHACANCERSC_NEW.DESC_HLBW
     *
     * @mbg.generated Wed Aug 08 21:22:13 KST 2018
     */
    public void setDeschlbw(String deschlbw) {
        this.deschlbw = deschlbw;
    }
}