package com.medi.hs.model;

import java.util.Date;

public class HsLabb42 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.ID
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private Short id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.JUBSJUBNO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String jubsjubno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.SDATE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String sdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.NO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private Short no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.CODE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.KNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String kname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.ENAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String ename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.SNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String sname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.VALUE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.MEMO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.DECISION
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String decision;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.STYLE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String style;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.LOW_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String lowMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.HIGH_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String highMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.LOW_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String lowWoman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.HIGH_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String highWoman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.REFCHAR
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String refChar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.DAT_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private Date datInsert;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column MEDI.HS_LABB42.COD_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	private String codInsert;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.ID
	 * @return  the value of MEDI.HS_LABB42.ID
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.ID
	 * @param id  the value for MEDI.HS_LABB42.ID
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setId(Short id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.JUBSJUBNO
	 * @return  the value of MEDI.HS_LABB42.JUBSJUBNO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getJubsjubno() {
		return jubsjubno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.JUBSJUBNO
	 * @param jubsjubno  the value for MEDI.HS_LABB42.JUBSJUBNO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setJubsjubno(String jubsjubno) {
		this.jubsjubno = jubsjubno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.SDATE
	 * @return  the value of MEDI.HS_LABB42.SDATE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getSdate() {
		return sdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.SDATE
	 * @param sdate  the value for MEDI.HS_LABB42.SDATE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setSdate(String sdate) {
		this.sdate = sdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.NO
	 * @return  the value of MEDI.HS_LABB42.NO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public Short getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.NO
	 * @param no  the value for MEDI.HS_LABB42.NO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setNo(Short no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.CODE
	 * @return  the value of MEDI.HS_LABB42.CODE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.CODE
	 * @param code  the value for MEDI.HS_LABB42.CODE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.KNAME
	 * @return  the value of MEDI.HS_LABB42.KNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getKname() {
		return kname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.KNAME
	 * @param kname  the value for MEDI.HS_LABB42.KNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setKname(String kname) {
		this.kname = kname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.ENAME
	 * @return  the value of MEDI.HS_LABB42.ENAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getEname() {
		return ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.ENAME
	 * @param ename  the value for MEDI.HS_LABB42.ENAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setEname(String ename) {
		this.ename = ename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.SNAME
	 * @return  the value of MEDI.HS_LABB42.SNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getSname() {
		return sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.SNAME
	 * @param sname  the value for MEDI.HS_LABB42.SNAME
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.VALUE
	 * @return  the value of MEDI.HS_LABB42.VALUE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.VALUE
	 * @param value  the value for MEDI.HS_LABB42.VALUE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.MEMO
	 * @return  the value of MEDI.HS_LABB42.MEMO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.MEMO
	 * @param memo  the value for MEDI.HS_LABB42.MEMO
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.DECISION
	 * @return  the value of MEDI.HS_LABB42.DECISION
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getDecision() {
		return decision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.DECISION
	 * @param decision  the value for MEDI.HS_LABB42.DECISION
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setDecision(String decision) {
		this.decision = decision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.STYLE
	 * @return  the value of MEDI.HS_LABB42.STYLE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getStyle() {
		return style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.STYLE
	 * @param style  the value for MEDI.HS_LABB42.STYLE
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setStyle(String style) {
		this.style = style;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.LOW_MAN
	 * @return  the value of MEDI.HS_LABB42.LOW_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getLowMan() {
		return lowMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.LOW_MAN
	 * @param lowMan  the value for MEDI.HS_LABB42.LOW_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setLowMan(String lowMan) {
		this.lowMan = lowMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.HIGH_MAN
	 * @return  the value of MEDI.HS_LABB42.HIGH_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getHighMan() {
		return highMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.HIGH_MAN
	 * @param highMan  the value for MEDI.HS_LABB42.HIGH_MAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setHighMan(String highMan) {
		this.highMan = highMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.LOW_WOMAN
	 * @return  the value of MEDI.HS_LABB42.LOW_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getLowWoman() {
		return lowWoman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.LOW_WOMAN
	 * @param lowWoman  the value for MEDI.HS_LABB42.LOW_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setLowWoman(String lowWoman) {
		this.lowWoman = lowWoman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.HIGH_WOMAN
	 * @return  the value of MEDI.HS_LABB42.HIGH_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getHighWoman() {
		return highWoman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.HIGH_WOMAN
	 * @param highWoman  the value for MEDI.HS_LABB42.HIGH_WOMAN
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setHighWoman(String highWoman) {
		this.highWoman = highWoman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.REFCHAR
	 * @return  the value of MEDI.HS_LABB42.REFCHAR
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getRefChar() {
		return refChar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.REFCHAR
	 * @param refChar  the value for MEDI.HS_LABB42.REFCHAR
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setRefChar(String refChar) {
		this.refChar = refChar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.DAT_INSERT
	 * @return  the value of MEDI.HS_LABB42.DAT_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public Date getDatInsert() {
		return datInsert;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.DAT_INSERT
	 * @param datInsert  the value for MEDI.HS_LABB42.DAT_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setDatInsert(Date datInsert) {
		this.datInsert = datInsert;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column MEDI.HS_LABB42.COD_INSERT
	 * @return  the value of MEDI.HS_LABB42.COD_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public String getCodInsert() {
		return codInsert;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column MEDI.HS_LABB42.COD_INSERT
	 * @param codInsert  the value for MEDI.HS_LABB42.COD_INSERT
	 * @mbg.generated  Wed Jul 04 18:38:47 KST 2018
	 */
	public void setCodInsert(String codInsert) {
		this.codInsert = codInsert;
	}
}