package com.medi.hs.model;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.TB_USER.U_ID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.TB_USER.U_PASSWORD
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.TB_USER.U_NAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.TB_USER.U_BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.TB_USER.U_ID
     *
     * @return the value of MOBILE.TB_USER.U_ID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.TB_USER.U_ID
     *
     * @param id the value for MOBILE.TB_USER.U_ID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.TB_USER.U_PASSWORD
     *
     * @return the value of MOBILE.TB_USER.U_PASSWORD
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.TB_USER.U_PASSWORD
     *
     * @param password the value for MOBILE.TB_USER.U_PASSWORD
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.TB_USER.U_NAME
     *
     * @return the value of MOBILE.TB_USER.U_NAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.TB_USER.U_NAME
     *
     * @param name the value for MOBILE.TB_USER.U_NAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.TB_USER.U_BIRTHDAY
     *
     * @return the value of MOBILE.TB_USER.U_BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.TB_USER.U_BIRTHDAY
     *
     * @param birthday the value for MOBILE.TB_USER.U_BIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
}