package com.medi.hs.model;

import java.util.Date;

public class Webregistpatient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.REGISTWEBPATIENTID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String registWebPatientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.RECEIPTDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private Date receiptDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.PATIENTNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String patientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.PATIENTMOBILENO
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String patientMobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.PATIENTBIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private Date patientBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.PATIENTGENDER
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String patientGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.PATIENTEMAIL
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String patientEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.AGREMENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String agrement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.REGISTEDBYNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String registedByName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.REGISTEDDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private Date registedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOBILE.WEBREGISTPATIENT.STATUS
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.REGISTWEBPATIENTID
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.REGISTWEBPATIENTID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getRegistWebPatientId() {
        return registWebPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.REGISTWEBPATIENTID
     *
     * @param registWebPatientId the value for MOBILE.WEBREGISTPATIENT.REGISTWEBPATIENTID
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setRegistWebPatientId(String registWebPatientId) {
        this.registWebPatientId = registWebPatientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.RECEIPTDATE
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.RECEIPTDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public Date getReceiptDate() {
        return receiptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.RECEIPTDATE
     *
     * @param receiptDate the value for MOBILE.WEBREGISTPATIENT.RECEIPTDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setReceiptDate(Date receiptDate) {
        this.receiptDate = receiptDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTNAME
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.PATIENTNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getPatientName() {
        return patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTNAME
     *
     * @param patientName the value for MOBILE.WEBREGISTPATIENT.PATIENTNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTMOBILENO
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.PATIENTMOBILENO
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getPatientMobileNo() {
        return patientMobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTMOBILENO
     *
     * @param patientMobileNo the value for MOBILE.WEBREGISTPATIENT.PATIENTMOBILENO
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPatientMobileNo(String patientMobileNo) {
        this.patientMobileNo = patientMobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTBIRTHDAY
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.PATIENTBIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public Date getPatientBirthday() {
        return patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTBIRTHDAY
     *
     * @param patientBirthday the value for MOBILE.WEBREGISTPATIENT.PATIENTBIRTHDAY
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPatientBirthday(Date patientBirthday) {
        this.patientBirthday = patientBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTGENDER
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.PATIENTGENDER
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getPatientGender() {
        return patientGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTGENDER
     *
     * @param patientGender the value for MOBILE.WEBREGISTPATIENT.PATIENTGENDER
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPatientGender(String patientGender) {
        this.patientGender = patientGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTEMAIL
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.PATIENTEMAIL
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getPatientEmail() {
        return patientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.PATIENTEMAIL
     *
     * @param patientEmail the value for MOBILE.WEBREGISTPATIENT.PATIENTEMAIL
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setPatientEmail(String patientEmail) {
        this.patientEmail = patientEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.AGREMENT
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.AGREMENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getAgrement() {
        return agrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.AGREMENT
     *
     * @param agrement the value for MOBILE.WEBREGISTPATIENT.AGREMENT
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setAgrement(String agrement) {
        this.agrement = agrement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.REGISTEDBYNAME
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.REGISTEDBYNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getRegistedByName() {
        return registedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.REGISTEDBYNAME
     *
     * @param registedByName the value for MOBILE.WEBREGISTPATIENT.REGISTEDBYNAME
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setRegistedByName(String registedByName) {
        this.registedByName = registedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.REGISTEDDATE
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.REGISTEDDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public Date getRegistedDate() {
        return registedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.REGISTEDDATE
     *
     * @param registedDate the value for MOBILE.WEBREGISTPATIENT.REGISTEDDATE
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setRegistedDate(Date registedDate) {
        this.registedDate = registedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOBILE.WEBREGISTPATIENT.STATUS
     *
     * @return the value of MOBILE.WEBREGISTPATIENT.STATUS
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOBILE.WEBREGISTPATIENT.STATUS
     *
     * @param status the value for MOBILE.WEBREGISTPATIENT.STATUS
     *
     * @mbg.generated Wed Aug 08 21:30:02 KST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}