package org.ohjic.flower.dao;

import org.ohjic.flower.model.Admin;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    int deleteByPrimaryKey(Integer adminSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    Admin selectByPrimaryKey(Integer adminSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    int updateByPrimaryKey(Admin record);
    
    Admin selectByAdmin(Admin admin);
}