package org.ohjic.flower.dao;

import java.util.List;

import org.ohjic.flower.model.Article;
import org.ohjic.flower.model.ArticleSearch;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int deleteByPrimaryKey(Integer articleSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    Article selectByPrimaryKey(Integer articleSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated Thu Jul 28 11:14:45 KST 2016
     */
    int updateByPrimaryKey(Article record);

	List<Article> selectList(ArticleSearch articleSearch);

	int countList(ArticleSearch articleSearch);
}