package org.ohjic.flower.model;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_seq
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    private Integer adminSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_role
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    private Integer userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.reg_time
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_seq
     *
     * @return the value of admin.admin_seq
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public Integer getAdminSeq() {
        return adminSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_seq
     *
     * @param adminSeq the value for admin.admin_seq
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public void setAdminSeq(Integer adminSeq) {
        this.adminSeq = adminSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param userId the value for admin.admin_id
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_role
     *
     * @return the value of admin.admin_role
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public Integer getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_role
     *
     * @param userName the value for admin.admin_role
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public void setUserName(Integer userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.reg_time
     *
     * @return the value of admin.reg_time
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.reg_time
     *
     * @param regTime the value for admin.reg_time
     *
     * @mbggenerated Tue Jul 26 16:37:02 KST 2016
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}