package org.ohjic.flower.model;

public class NoteMessage {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.message_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private Integer messageSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.from_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private Integer fromUserSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.to_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private Integer toUserSeq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.send_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private String sendTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.read_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private String readTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note_message.content
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.message_seq
	 * @return  the value of note_message.message_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public Integer getMessageSeq() {
		return messageSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.message_seq
	 * @param messageSeq  the value for note_message.message_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setMessageSeq(Integer messageSeq) {
		this.messageSeq = messageSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.from_user_seq
	 * @return  the value of note_message.from_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public Integer getFromUserSeq() {
		return fromUserSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.from_user_seq
	 * @param fromUserSeq  the value for note_message.from_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setFromUserSeq(Integer fromUserSeq) {
		this.fromUserSeq = fromUserSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.to_user_seq
	 * @return  the value of note_message.to_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public Integer getToUserSeq() {
		return toUserSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.to_user_seq
	 * @param toUserSeq  the value for note_message.to_user_seq
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setToUserSeq(Integer toUserSeq) {
		this.toUserSeq = toUserSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.send_time
	 * @return  the value of note_message.send_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public String getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.send_time
	 * @param sendTime  the value for note_message.send_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setSendTime(String sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.read_time
	 * @return  the value of note_message.read_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public String getReadTime() {
		return readTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.read_time
	 * @param readTime  the value for note_message.read_time
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setReadTime(String readTime) {
		this.readTime = readTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note_message.content
	 * @return  the value of note_message.content
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note_message.content
	 * @param content  the value for note_message.content
	 * @mbggenerated  Wed Jul 27 10:18:42 KST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	private User from;
    
    private User to;

    public User getFrom() {
		return from;
	}

	public void setFrom(User from) {
		this.from = from;
	}

	public User getTo() {
		return to;
	}

	public void setTo(User to) {
		this.to = to;
	}
}