SET DEFINE OFF;
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, 
    MOBIL_PASS, MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, 
    MAILING, IP_ADDR)
 Values
   (NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, 
    MOBIL_PASS, MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, 
    MAILING, IP_ADDR)
 Values
   (NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, 
    MOBIL_PASS, MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, 
    MAILING, IP_ADDR)
 Values
   (NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, 
    MOBIL_PASS, MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, 
    MAILING, IP_ADDR)
 Values
   (NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, 
    MOBIL_PASS, MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, 
    MAILING, IP_ADDR)
 Values
   (NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL);
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_ID, MOBIL_EMAIL, MOBIL_PASS, 
    MOBIL_TEL1)
 Values
   ('박주현', '881027', 'angel', 'angel@hanshin.com', '1234', 
    '0010-2038-2770');
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_ID, MOBIL_EMAIL, MOBIL_TEL1, MOBIL_TEL2, 
    MOBIL_TEL3, SMS_OK, MAILING)
 Values
   ('테스트', 'test', 'test@naver.com', '010', '1111', 
    '2222', 'Y', 'Y');
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_ID, MOBIL_EMAIL, MOBIL_PASS, MOBIL_TEL1, 
    MOBIL_TEL2, MOBIL_TEL3, SMS_OK, MAILING)
 Values
   ('테스트1', 'test1', 'test1@naver.com', '0000', '010-1111-2222', 
    '010-2222-3333', '010-3333-4444', '1', '1');
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_SEX, MOBIL_ID, MOBIL_EMAIL, MOBIL_PASS, 
    MOBIL_TEL1, SMS_OK, MAILING)
 Values
   ('김소라', 'F', 'test2', 'test2@naver.com', '9af15b336e6a9619928537df30b2e6a2376569fcf9d7e773eccede65606529a0', 
    '010-3345-4428', '1', '1');
Insert into MOBILE.MOBIL_PERSONAL
   (MOBIL_PERS_NM, MOBIL_PERS_NO, MOBIL_ID, MOBIL_EMAIL, MOBIL_PASS, 
    MOBIL_TEL1, MOBIL_TEL2, MOBIL_TEL3, SMS_OK, MAILING)
 Values
   ('김한신', '990102', 'han', 'hanshin@hanshin.com', '1234', 
    '010-0000-0000', '010-1111-1111', '010-2222-2222', '1', '1');
COMMIT;
